import type { MembershipTier, MembershipFeature } from "@/types";

export const membershipTiers: MembershipTier[] = [
  {
    tier: "free",
    name: "Free",
    price: 0,
    period: "month",
    currency: "AUD",
    description: "Browse our plans and meals. Sign up to order.",
    features: [
      "Browse all plans and meals",
      "View nutrition information",
      "Cooking method and dietary filters",
    ],
    ctaText: "Browse Plans",
  },
  {
    tier: "standard",
    name: "Standard",
    price: 9.99,
    period: "month",
    currency: "AUD",
    description: "Full access to ordering, guides, and tracking.",
    features: [
      "Order any plan or build your own meals",
      "Step-by-step cooking guides with images",
      "Favourites and reorder",
      "Macro tracking with health app sync",
      "Allergen and dietary filtering",
      "Cooking method filters",
    ],
    ctaText: "Join Standard",
  },
  {
    tier: "premium",
    name: "Premium",
    price: 29.99,
    period: "month",
    currency: "AUD",
    description: "Everything plus AI tools, custom portioning, and priority delivery.",
    features: [
      "Everything in Standard",
      "AI Macro Wizard (personalised macro calculator)",
      "Custom portioning to exact macros",
      "Smart Swap (swap any ingredient)",
      "Priority delivery window selection",
      "Monthly Global Flavour box included free",
      "Organic-only option toggle",
      "10% discount on all meal orders",
      "Free delivery on all orders",
      "Early access to new meals",
    ],
    highlighted: true,
    ctaText: "Join Premium",
  },
];

export const membershipFeatures: MembershipFeature[] = [
  { name: "Browse plans and meals", free: true, standard: true, premium: true },
  { name: "View nutrition info", free: true, standard: true, premium: true },
  { name: "Cooking method filters", free: true, standard: true, premium: true },
  { name: "Order meals and plans", free: false, standard: true, premium: true },
  { name: "Step-by-step cooking guides", free: false, standard: true, premium: true },
  { name: "Favourites and reorder", free: false, standard: true, premium: true },
  { name: "Macro tracking + health app sync", free: false, standard: true, premium: true },
  { name: "AI Macro Wizard", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Custom portioning to exact macros", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Smart Swap ingredients", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Priority delivery window", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Global Flavour box (free)", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Organic-only toggle", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "10% discount on all orders", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Free delivery", free: false, standard: false, premium: true, premiumOnly: true },
  { name: "Early access to new meals", free: false, standard: false, premium: true, premiumOnly: true },
];
