import type { Sauce, SideSauce, SaladAddOn } from "@/types";

export const coreSauces: Sauce[] = [
  {
    code: "garlic-herb-butter",
    name: "Garlic Herb Butter",
    style: "Rich, savoury, classic",
    bestWith: "Steaks, chicken breast, roasted vegetables, baby potatoes",
    cookingMethods: "Pan, oven, BBQ",
    ingredients: [
      { name: "Butter, unsalted", quantity: "20g" },
      { name: "Garlic, fresh minced", quantity: "4g" },
      { name: "Flat-leaf parsley, fresh chopped", quantity: "3g" },
      { name: "Thyme, fresh", quantity: "1g" },
      { name: "Chives, fresh chopped", quantity: "1g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper, cracked", quantity: "0.5g" },
    ],
    allergens: ["dairy"],
    dietary: { gf: "yes", df: "no", lf: "swap" },
    nutritionPerServe: { calories: 152, protein: 0.3, carbs: 0.8, fat: 16.4, fiber: 0.1, sodium: 125 },
    servingSize: 30,
  },
  {
    code: "lemon-herb",
    name: "Lemon Herb Dressing",
    style: "Light, fresh, citrusy",
    bestWith: "Grilled chicken, salad bowls, light lunch plates, lamb leg steaks",
    cookingMethods: "Drizzle after cooking",
    ingredients: [
      { name: "Extra virgin olive oil", quantity: "15g" },
      { name: "Lemon juice, fresh", quantity: "5g" },
      { name: "Lemon zest", quantity: "1g" },
      { name: "Garlic, minced", quantity: "1g" },
      { name: "Dried oregano", quantity: "0.5g" },
      { name: "Flat-leaf parsley, chopped", quantity: "1g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Apple cider vinegar", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 125, protein: 0.1, carbs: 0.9, fat: 13.5, fiber: 0.1, sodium: 120 },
    servingSize: 25,
  },
  {
    code: "smoky-bbq",
    name: "Smoky BBQ Marinade",
    style: "Bold, smoky, slightly sweet (from tomato, not sugar)",
    bestWith: "Chicken thighs, drumsticks, beef mince, tray bakes",
    cookingMethods: "Air fryer, oven, BBQ, pan",
    ingredients: [
      { name: "Tomato paste", quantity: "10g" },
      { name: "Apple cider vinegar", quantity: "4g" },
      { name: "Smoked paprika", quantity: "2g" },
      { name: "Garlic powder", quantity: "1.5g" },
      { name: "Onion powder", quantity: "1.5g" },
      { name: "Ground cumin", quantity: "1g" },
      { name: "Mustard powder", quantity: "0.5g" },
      { name: "Water", quantity: "6g" },
      { name: "Olive oil", quantity: "2g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Cayenne pepper", quantity: "0.5g" },
    ],
    allergens: ["mustard"],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 38, protein: 1.1, carbs: 4.2, fat: 2.1, fiber: 0.8, sodium: 165 },
    servingSize: 30,
  },
  {
    code: "chimichurri",
    name: "Chimichurri",
    style: "Herbaceous, tangy, punchy",
    bestWith: "Steaks (especially ribeye, rump), lamb chops, grilled chicken",
    cookingMethods: "Drizzle after cooking or as marinade before grilling",
    ingredients: [
      { name: "Fresh parsley, finely chopped", quantity: "7g" },
      { name: "Fresh coriander, finely chopped", quantity: "3g" },
      { name: "Extra virgin olive oil", quantity: "8g" },
      { name: "Red wine vinegar", quantity: "3g" },
      { name: "Garlic, minced", quantity: "1.5g" },
      { name: "Red chilli flakes", quantity: "0.5g" },
      { name: "Dried oregano", quantity: "0.5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Lemon juice", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 78, protein: 0.4, carbs: 1.1, fat: 8.1, fiber: 0.5, sodium: 118 },
    servingSize: 25,
  },
  {
    code: "peri-peri",
    name: "Peri-Peri Marinade",
    style: "Spicy, citrusy, African-Portuguese",
    bestWith: "Chicken (all cuts, especially thighs and drumsticks), wings",
    cookingMethods: "Air fryer, oven, BBQ, pan",
    ingredients: [
      { name: "Red capsicum, roasted and pureed", quantity: "8g" },
      { name: "Olive oil", quantity: "5g" },
      { name: "Lemon juice, fresh", quantity: "4g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Bird's eye chilli, minced", quantity: "1.5g" },
      { name: "Smoked paprika", quantity: "2g" },
      { name: "Dried oregano", quantity: "1g" },
      { name: "Apple cider vinegar", quantity: "3g" },
      { name: "Onion powder", quantity: "1g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Fresh basil, chopped", quantity: "1g" },
      { name: "Lemon zest", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 52, protein: 0.5, carbs: 2.8, fat: 4.3, fiber: 0.6, sodium: 130 },
    servingSize: 30,
  },
  {
    code: "teriyaki",
    name: "Teriyaki-Style Glaze",
    style: "Savoury, umami, slightly glossy",
    bestWith: "Stir-fry (chicken, beef strips), rice bowls, noodle-style dishes",
    cookingMethods: "Pan, wok (stir-fry)",
    ingredients: [
      { name: "Tamari (gluten-free soy sauce)", quantity: "8g" },
      { name: "Rice wine vinegar", quantity: "4g" },
      { name: "Sesame oil", quantity: "2g" },
      { name: "Fresh ginger, minced", quantity: "2g" },
      { name: "Garlic, minced", quantity: "1.5g" },
      { name: "Water", quantity: "4g" },
      { name: "Arrowroot powder", quantity: "1.5g" },
      { name: "Toasted sesame seeds", quantity: "1g" },
      { name: "Spring onion, sliced", quantity: "1g" },
    ],
    allergens: ["soy", "sesame"],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 42, protein: 1.8, carbs: 3.1, fat: 2.4, fiber: 0.2, sodium: 410 },
    servingSize: 25,
  },
  {
    code: "coconut-curry",
    name: "Coconut Curry Sauce",
    style: "Creamy, aromatic, mild-medium heat",
    bestWith: "Chicken breast, lamb shoulder (slow cook), beef strips, served with rice",
    cookingMethods: "Pan, slow cooker, oven",
    ingredients: [
      { name: "Coconut cream", quantity: "25g" },
      { name: "Tomato passata", quantity: "8g" },
      { name: "Onion, finely diced", quantity: "4g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Fresh ginger, minced", quantity: "2g" },
      { name: "Ground turmeric", quantity: "1g" },
      { name: "Ground cumin", quantity: "1g" },
      { name: "Ground coriander", quantity: "1g" },
      { name: "Garam masala", quantity: "0.5g" },
      { name: "Coconut oil", quantity: "2g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Fresh coriander, chopped", quantity: "1g" },
      { name: "Lime juice", quantity: "1g" },
      { name: "Chilli flakes", quantity: "0.5g" },
      { name: "Water", quantity: "1.5g" },
    ],
    allergens: ["tree-nut"],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 98, protein: 1.1, carbs: 3.4, fat: 9.2, fiber: 0.6, sodium: 128 },
    servingSize: 50,
  },
  {
    code: "tomato-curry",
    name: "Tomato Herb Curry Sauce",
    style: "Rich, warming, tomato-forward (no coconut)",
    bestWith: "Beef mince, chicken thighs, lamb mince, kofta, with rice or potato",
    cookingMethods: "Pan, oven, slow cooker",
    ingredients: [
      { name: "Tomato passata", quantity: "25g" },
      { name: "Onion, finely diced", quantity: "6g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Fresh ginger, minced", quantity: "1.5g" },
      { name: "Olive oil", quantity: "3g" },
      { name: "Ground cumin", quantity: "1g" },
      { name: "Ground coriander", quantity: "1g" },
      { name: "Smoked paprika", quantity: "0.5g" },
      { name: "Ground turmeric", quantity: "0.5g" },
      { name: "Chilli powder", quantity: "0.5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Fresh coriander, chopped", quantity: "1g" },
      { name: "Water", quantity: "7g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 45, protein: 1.0, carbs: 4.8, fat: 2.6, fiber: 1.0, sodium: 145 },
    servingSize: 50,
  },
  {
    code: "shawarma",
    name: "Shawarma Spice Blend",
    style: "Warm, aromatic, Middle Eastern",
    bestWith: "Chicken thighs, lamb leg, kofta, served with couscous or rice",
    cookingMethods: "Oven, pan, air fryer, BBQ",
    ingredients: [
      { name: "Ground cumin", quantity: "2g" },
      { name: "Ground coriander", quantity: "1.5g" },
      { name: "Smoked paprika", quantity: "1.5g" },
      { name: "Ground turmeric", quantity: "1g" },
      { name: "Garlic powder", quantity: "1g" },
      { name: "Ground cinnamon", quantity: "0.5g" },
      { name: "Ground cardamom", quantity: "0.3g" },
      { name: "Ground black pepper", quantity: "0.5g" },
      { name: "Sea salt", quantity: "0.7g" },
      { name: "Dried oregano", quantity: "0.5g" },
      { name: "Cayenne pepper", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 22, protein: 0.8, carbs: 3.2, fat: 0.8, fiber: 1.2, sodium: 170 },
    servingSize: 10,
  },
  {
    code: "korean",
    name: "Korean-Inspired Marinade",
    style: "Savoury, umami, slightly sweet from pear (no sugar)",
    bestWith: "Beef strips (bulgogi-style), chicken thighs, stir-fry bowls",
    cookingMethods: "Pan, wok (stir-fry), BBQ",
    ingredients: [
      { name: "Tamari (gluten-free soy sauce)", quantity: "6g" },
      { name: "Sesame oil", quantity: "3g" },
      { name: "Pear puree", quantity: "4g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Fresh ginger, minced", quantity: "2g" },
      { name: "Rice wine vinegar", quantity: "2g" },
      { name: "Gochugaru (Korean chilli flakes)", quantity: "1.5g" },
      { name: "Toasted sesame seeds", quantity: "1g" },
      { name: "Spring onion, sliced", quantity: "1.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Water", quantity: "1.5g" },
    ],
    allergens: ["soy", "sesame"],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 48, protein: 1.5, carbs: 3.4, fat: 3.0, fiber: 0.4, sodium: 380 },
    servingSize: 25,
  },
  {
    code: "med-herb",
    name: "Mediterranean Herb Marinade",
    style: "Herby, bright, garlicky, olive oil base",
    bestWith: "Lamb (all cuts), chicken thighs, roasted vegetables, tray bakes",
    cookingMethods: "Oven, air fryer, BBQ, pan",
    ingredients: [
      { name: "Extra virgin olive oil", quantity: "10g" },
      { name: "Lemon juice, fresh", quantity: "3g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Dried oregano", quantity: "1.5g" },
      { name: "Dried rosemary, crushed", quantity: "1g" },
      { name: "Dried thyme", quantity: "1g" },
      { name: "Smoked paprika", quantity: "0.5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Lemon zest", quantity: "0.5g" },
      { name: "Red wine vinegar", quantity: "4g" },
      { name: "Dried basil", quantity: "0.5g" },
      { name: "Onion powder", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 92, protein: 0.2, carbs: 1.3, fat: 9.6, fiber: 0.3, sodium: 122 },
    servingSize: 25,
  },
  {
    code: "simple-spo",
    name: "Salt, Pepper & Olive Oil",
    style: "Clean, simple, lets the protein speak",
    bestWith: "Any premium cut, simple grilled chicken, any meal where protein is the star",
    cookingMethods: "Pan, BBQ, air fryer, oven",
    ingredients: [
      { name: "Extra virgin olive oil", quantity: "10g" },
      { name: "Sea salt flakes", quantity: "2g" },
      { name: "Cracked black pepper", quantity: "2g" },
      { name: "Garlic powder", quantity: "0.5g" },
      { name: "Lemon juice", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 88, protein: 0, carbs: 0.2, fat: 9.8, fiber: 0, sodium: 390 },
    servingSize: 15,
  },
];

export const sideSauces: SideSauce[] = [
  {
    code: "side-mushroom",
    name: "Creamy Mushroom Sauce",
    description: "Rich, creamy, earthy mushroom sauce. Heat in saucepan 2-3 min.",
    style: "Rich, creamy, earthy",
    bestWith: "Steaks (all cuts), chicken breast, lamb chops",
    heatingInstructions: "Saucepan, 2-3 min on medium. Stir until warmed through.",
    ingredients: [
      { name: "Button mushrooms, finely sliced", quantity: "20g" },
      { name: "Thickened cream", quantity: "18g" },
      { name: "Olive oil", quantity: "3g" },
      { name: "Garlic, minced", quantity: "2g" },
      { name: "Fresh thyme", quantity: "1g" },
      { name: "Onion, finely diced", quantity: "5g" },
      { name: "Dijon mustard", quantity: "2g" },
      { name: "Chicken stock (halal)", quantity: "5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Cornflour", quantity: "1g" },
      { name: "Water", quantity: "2g" },
    ],
    allergens: ["dairy", "mustard"],
    dietary: { gf: "yes", df: "no", lf: "swap" },
    nutritionPerServe: { calories: 85, protein: 1.8, carbs: 3.2, fat: 7.2, fiber: 0.4, sodium: 180 },
    servingSize: 60,
  },
  {
    code: "side-pepper",
    name: "Pepper Sauce",
    description: "Bold, peppery, slightly creamy sauce. Heat in saucepan 2-3 min.",
    style: "Bold, peppery, slightly creamy",
    bestWith: "Steaks (rump, sirloin, fillet), lamb leg steak",
    heatingInstructions: "Saucepan, 2-3 min on medium.",
    ingredients: [
      { name: "Thickened cream", quantity: "15g" },
      { name: "Cracked black peppercorns", quantity: "3g" },
      { name: "Green peppercorns (brined)", quantity: "3g" },
      { name: "Olive oil", quantity: "2g" },
      { name: "Garlic, minced", quantity: "1.5g" },
      { name: "Onion, finely diced", quantity: "5g" },
      { name: "Halal beef stock", quantity: "10g" },
      { name: "Dijon mustard", quantity: "1.5g" },
      { name: "Non-alcoholic brandy essence", quantity: "1g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Cornflour", quantity: "1g" },
      { name: "Water", quantity: "6g" },
    ],
    allergens: ["dairy", "mustard"],
    dietary: { gf: "yes", df: "no", lf: "swap" },
    nutritionPerServe: { calories: 72, protein: 1.2, carbs: 2.8, fat: 6.0, fiber: 0.5, sodium: 195 },
    servingSize: 50,
  },
  {
    code: "side-gravy",
    name: "Gravy",
    description: "Classic, rich, savoury gravy. Heat in saucepan 2-3 min. Add water if too thick.",
    style: "Classic, rich, savoury",
    bestWith: "Any roast, mash, potatoes, chicken, lamb",
    heatingInstructions: "Saucepan, 2-3 min. Splash of water if too thick.",
    ingredients: [
      { name: "Halal beef stock", quantity: "20g" },
      { name: "Halal chicken stock", quantity: "10g" },
      { name: "Onion, finely diced", quantity: "5g" },
      { name: "Garlic, minced", quantity: "1g" },
      { name: "Olive oil", quantity: "2g" },
      { name: "Cornflour", quantity: "2g" },
      { name: "Fresh thyme", quantity: "0.5g" },
      { name: "Tomato paste", quantity: "1.5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Water", quantity: "6.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 32, protein: 1.5, carbs: 3.0, fat: 1.6, fiber: 0.1, sodium: 320 },
    servingSize: 50,
  },
];

export const saladAddOns: SaladAddOn[] = [
  {
    code: "salad-garden",
    name: "Garden Salad",
    description: "Crisp mixed leaves, cherry tomatoes, cucumber, red onion, with a light lemon olive oil dressing.",
    ingredients: [
      { name: "Mixed salad leaves", quantity: "50g" },
      { name: "Cherry tomatoes, halved", quantity: "30g" },
      { name: "Cucumber, sliced", quantity: "25g" },
      { name: "Red onion, thinly sliced", quantity: "10g" },
      { name: "Carrot, shredded", quantity: "5g" },
    ],
    dressing: [
      { name: "Extra virgin olive oil", quantity: "5g" },
      { name: "Lemon juice", quantity: "3g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Dried oregano", quantity: "0.5g" },
      { name: "Apple cider vinegar", quantity: "0.5g" },
    ],
    allergens: [],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 72, protein: 1.5, carbs: 6.8, fat: 4.5, fiber: 2.0, sodium: 135 },
  },
  {
    code: "salad-slaw",
    name: "Simple Slaw",
    description: "Crunchy shredded cabbage, carrot and spring onion with a tangy apple cider vinaigrette.",
    ingredients: [
      { name: "Green cabbage, finely shredded", quantity: "40g" },
      { name: "Red cabbage, finely shredded", quantity: "20g" },
      { name: "Carrot, shredded", quantity: "20g" },
      { name: "Spring onion, sliced", quantity: "5g" },
    ],
    dressing: [
      { name: "Apple cider vinegar", quantity: "5g" },
      { name: "Extra virgin olive oil", quantity: "5g" },
      { name: "Dijon mustard", quantity: "1.5g" },
      { name: "Sea salt", quantity: "0.5g" },
      { name: "Black pepper", quantity: "0.5g" },
      { name: "Lemon juice", quantity: "1.5g" },
      { name: "Toasted sesame seeds", quantity: "1g" },
    ],
    allergens: ["mustard", "sesame"],
    dietary: { gf: "yes", df: "yes", lf: "yes" },
    nutritionPerServe: { calories: 78, protein: 1.3, carbs: 5.5, fat: 5.8, fiber: 2.2, sodium: 150 },
  },
];

export function getSauceByCode(code: string): Sauce | undefined {
  return coreSauces.find((s) => s.code === code);
}
