import type { Plan } from "@/types";

export const bulkUpPlan: Plan = {
  slug: "the-bulk-up",
  name: "The Bulk Up",
  tagline: "Mass gain meals built for serious bulking.",
  goal: "muscle-gain",
  description:
    "High-calorie, protein-packed meals designed for muscle gain and bulking. Three meals a day including breakfast, with generous portions of chicken thighs, beef ribeye, lamb shoulder, and premium carbs. Built for serious lifters who need real food to fuel growth.",
  difficulty: "intermediate",
  targetCalories: 3200,
  macroSplit: { protein: 30, carbs: 50, fat: 20 },
  mealsPerDay: 3,
  includesBreakfast: true,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    // ===================== Day 1 — Monday =====================
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "protein-pancakes-with-oats-and-honey-drizzle",
          name: "Protein Pancakes with Oats and Honey Drizzle",
          description:
            "Stack of thick protein pancakes from our custom batter, served with a side of rolled oats topped with a drizzle of raw honey and sliced banana.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "protein-pancake-batter",
              name: "Protein pancake batter",
              quantity: 200,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "raw-honey-sachet",
              name: "Raw honey sachet",
              quantity: 15,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "banana-sliced",
              name: "Banana, sliced",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: {
            calories: 738,
            protein: 52,
            carbs: 105,
            fat: 14,
            fiber: 13,
            sodium: 625,
          },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Prepare oats: pour hot water or milk over, stand 3 min",
            "Heat non-stick pan to medium",
            "Pour batter in ~2 tbsp portions, cook 2 min per side until golden",
            "Stack 4-5 pancakes, top oats with banana and honey drizzle",
          ],
        },
        {
          slug: "chicken-thigh-and-pasta-with-roasted-peppers",
          name: "Chicken Thigh and Pasta with Roasted Peppers",
          description:
            "Seasoned chicken thighs cooked with penne pasta and roasted sweet peppers in a simple tomato herb sauce.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-thigh-boneless",
              name: "Chicken thigh, boneless",
              quantity: 250,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "pasta-penne",
              name: "Pasta (penne)",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "tomato-herb-curry-sauce",
              name: "Tomato herb curry sauce pouch",
              quantity: 50,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan", "oven"],
          cookTime: 25,
          difficulty: "intermediate",
          nutrition: {
            calories: 832,
            protein: 75,
            carbs: 65,
            fat: 30,
            fiber: 5,
            sodium: 410,
          },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions, drain",
            "Heat pan to medium-high, cook chicken thighs 5 min per side until golden",
            "Remove chicken, slice thickly",
            "In same pan, cook peppers 3 min",
            "Add tomato sauce pouch and pasta, toss to combine",
            "Return sliced chicken, stir through",
            "Optional: transfer to oven dish, bake 10 min at 200C for a baked finish",
          ],
        },
        {
          slug: "beef-ribeye-with-sweet-potato-mash-and-corn",
          name: "Beef Ribeye with Sweet Potato Mash and Corn",
          description:
            "Thick-cut ribeye steak pan-seared with garlic herb butter, served with creamy sweet potato mash and charred corn.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-ribeye",
              name: "Beef ribeye steak",
              quantity: 250,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, cubed for mash",
              quantity: 250,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "sweet-corn",
              name: "Sweet corn",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "garlic-herb-butter",
              name: "Garlic herb butter pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: {
            calories: 1020,
            protein: 65,
            carbs: 73,
            fat: 55,
            fiber: 10,
            sodium: 430,
          },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato cubes 12 min until soft, mash with fork",
            "Heat pan to high, sear ribeye 4 min per side for medium",
            "Place garlic herb butter disc on steak, rest 3 min",
            "Char corn in same pan 3-4 min",
            "Plate mash, steak with melting butter, and corn",
          ],
        },
      ],
      dailyTotals: {
        calories: 2590,
        protein: 192,
        carbs: 243,
        fat: 99,
        fiber: 28,
        sodium: 1465,
      },
    },

    // ===================== Day 2 — Tuesday =====================
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "rolled-oats-with-eggs-and-toast",
          name: "Rolled Oats with Eggs and Toast",
          description:
            "Hearty bowl of rolled oats with two fried free-range eggs on the side and a slice of sourdough toast.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 100,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "free-range-eggs",
              name: "Free-range eggs (x2)",
              quantity: 120,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "sourdough-bread",
              name: "Sourdough bread",
              quantity: 70,
              unit: "g",
              category: "carb",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: {
            calories: 620,
            protein: 28,
            carbs: 80,
            fat: 19,
            fiber: 11,
            sodium: 450,
          },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook oats with water or milk, microwave 3 min or stovetop 5 min",
            "Fry eggs in non-stick pan to preference",
            "Toast sourdough",
            "Serve oats in bowl, eggs and toast on the side",
          ],
        },
        {
          slug: "lamb-shoulder-slow-cook-with-white-rice-and-carrots",
          name: "Lamb Shoulder Slow-Cook with White Rice and Carrots",
          description:
            "Tender lamb shoulder slow-cooked in coconut curry sauce with carrots, served over a generous portion of white rice. Can also be oven-braised.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "lamb-shoulder",
              name: "Lamb shoulder, diced",
              quantity: 220,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "carrots",
              name: "Carrots, chunked",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "coconut-curry-sauce",
              name: "Coconut curry sauce pouch",
              quantity: 50,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["slow-cooker", "oven"],
          cookTime: 30,
          difficulty: "intermediate",
          nutrition: {
            calories: 870,
            protein: 58,
            carbs: 82,
            fat: 34,
            fiber: 5,
            sodium: 370,
          },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to high, brown lamb pieces on all sides (5 min)",
            "Transfer to oven-safe dish with carrots",
            "Pour coconut curry sauce over, add 50ml water",
            "Cover with foil, oven at 160C for 90 min (or slow cooker 4-6 hrs)",
            "Cook rice in last 15 min",
            "Serve lamb and carrots over rice with sauce",
          ],
        },
        {
          slug: "smoky-bbq-beef-mince-with-sweet-potato-mash-and-corn",
          name: "Smoky BBQ Beef Mince with Sweet Potato Mash and Corn",
          description:
            "Saucy BBQ beef mince piled over smooth sweet potato mash with a side of charred corn.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-mince-15",
              name: "Beef mince (15% fat)",
              quantity: 250,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, for mash",
              quantity: 200,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "sweet-corn",
              name: "Sweet corn",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "smoky-bbq-marinade",
              name: "Smoky BBQ marinade pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 810,
            protein: 52,
            carbs: 68,
            fat: 39,
            fiber: 9,
            sodium: 490,
          },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato 12 min, mash",
            "Brown beef mince in pan 5-6 min, drain excess fat",
            "Add BBQ sauce pouch, stir through, simmer 3 min",
            "Char corn in separate pan or alongside",
            "Plate mash, top with BBQ mince, corn on side",
          ],
        },
      ],
      dailyTotals: {
        calories: 2300,
        protein: 138,
        carbs: 230,
        fat: 92,
        fiber: 25,
        sodium: 1310,
      },
    },

    // ===================== Day 3 — Wednesday =====================
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "protein-pancakes-with-banana",
          name: "Protein Pancakes with Banana",
          description:
            "Protein pancakes served with sliced banana. Simple, fast, high protein start.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "protein-pancake-batter",
              name: "Protein pancake batter",
              quantity: 200,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "banana-sliced",
              name: "Banana, sliced",
              quantity: 100,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "raw-honey-sachet",
              name: "Raw honey sachet",
              quantity: 15,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: {
            calories: 525,
            protein: 45,
            carbs: 72,
            fat: 9,
            fiber: 5,
            sodium: 625,
          },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [],
        },
        {
          slug: "chicken-breast-with-peri-peri-white-rice-and-roasted-peppers",
          name: "Chicken Breast with Peri-Peri, White Rice and Roasted Peppers",
          description:
            "Peri-peri marinated chicken breast with a generous portion of white rice and colourful roasted peppers.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast",
              quantity: 220,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "peri-peri-marinade",
              name: "Peri-peri marinade pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "oven", "pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 680,
            protein: 73,
            carbs: 59,
            fat: 14,
            fiber: 3,
            sodium: 385,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "beef-sirloin-with-chimichurri-baby-potatoes-and-asparagus",
          name: "Beef Sirloin with Chimichurri, Baby Potatoes and Asparagus",
          description:
            "Thick sirloin steak with punchy chimichurri, halved baby potatoes and charred asparagus.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-sirloin",
              name: "Beef sirloin steak",
              quantity: 220,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "baby-potatoes",
              name: "Baby potatoes, halved",
              quantity: 200,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "asparagus",
              name: "Asparagus spears",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "chimichurri",
              name: "Chimichurri pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: {
            calories: 668,
            protein: 63,
            carbs: 38,
            fat: 30,
            fiber: 6,
            sodium: 320,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
      ],
      dailyTotals: {
        calories: 1873,
        protein: 181,
        carbs: 169,
        fat: 53,
        fiber: 14,
        sodium: 1330,
      },
    },

    // ===================== Day 4 — Thursday =====================
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "oats-with-eggs",
          name: "Oats with Eggs",
          description:
            "Large bowl of rolled oats with two scrambled free-range eggs folded through. Simple bulk fuel.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 100,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "free-range-eggs",
              name: "Free-range eggs (x2)",
              quantity: 120,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: {
            calories: 555,
            protein: 27,
            carbs: 68,
            fat: 19,
            fiber: 10,
            sodium: 280,
          },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "teriyaki-beef-strips-with-noodles-and-broccoli",
          name: "Teriyaki Beef Strips with Noodles and Broccoli",
          description:
            "Thin beef strips wok-fried in teriyaki glaze with broccoli, served over rice noodles.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "beef-rump",
              name: "Beef rump, thin strips",
              quantity: 220,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "rice-noodles",
              name: "Rice noodles",
              quantity: 120,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "broccoli",
              name: "Broccoli florets",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "teriyaki-glaze",
              name: "Teriyaki glaze pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: {
            calories: 688,
            protein: 66,
            carbs: 58,
            fat: 21,
            fiber: 4,
            sodium: 595,
          },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "lamb-cutlets-with-mediterranean-herbs-roasted-veg-and-pasta",
          name: "Lamb Cutlets with Mediterranean Herbs, Roasted Veg and Pasta",
          description:
            "Mediterranean herb-marinated lamb cutlets with roasted zucchini, peppers, and a generous serve of penne.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "lamb-cutlets",
              name: "Lamb cutlets (x3)",
              quantity: 210,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "pasta-penne",
              name: "Pasta (penne)",
              quantity: 130,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "zucchini",
              name: "Zucchini, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "med-herb-marinade",
              name: "Mediterranean herb marinade pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 25,
          difficulty: "intermediate",
          nutrition: {
            calories: 880,
            protein: 62,
            carbs: 64,
            fat: 42,
            fiber: 5,
            sodium: 360,
          },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
      ],
      dailyTotals: {
        calories: 2123,
        protein: 155,
        carbs: 190,
        fat: 82,
        fiber: 19,
        sodium: 1235,
      },
    },

    // ===================== Day 5 — Friday =====================
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "protein-pancakes-with-oats",
          name: "Protein Pancakes with Oats",
          description:
            "Protein pancakes stacked high with a side bowl of oats. Maximum morning fuel.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "protein-pancake-batter",
              name: "Protein pancake batter",
              quantity: 180,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "raw-honey-sachet",
              name: "Raw honey sachet",
              quantity: 15,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: {
            calories: 698,
            protein: 48,
            carbs: 100,
            fat: 13,
            fiber: 12,
            sodium: 565,
          },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [],
        },
        {
          slug: "chicken-thigh-tray-bake-with-root-vegetables-and-rice",
          name: "Chicken Thigh Tray Bake with Root Vegetables and Rice",
          description:
            "Juicy chicken thighs roasted on a tray with carrots, baby potatoes and zucchini in smoky BBQ marinade, served with rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-thigh-boneless",
              name: "Chicken thigh, boneless (x2)",
              quantity: 250,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "carrots",
              name: "Carrots, chunked",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "baby-potatoes",
              name: "Baby potatoes, halved",
              quantity: 120,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "zucchini",
              name: "Zucchini, chunked",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 120,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "smoky-bbq-marinade",
              name: "Smoky BBQ marinade pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["oven"],
          cookTime: 30,
          difficulty: "beginner",
          nutrition: {
            calories: 892,
            protein: 72,
            carbs: 80,
            fat: 32,
            fiber: 8,
            sodium: 480,
          },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "beef-fillet-with-simple-spo-green-beans-and-sweet-potato-mash",
          name: "Beef Fillet with Simple SPO, Green Beans and Sweet Potato Mash",
          description:
            "Premium beef fillet simply seasoned, pan-seared, served with steamed green beans and creamy sweet potato mash.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-fillet",
              name: "Beef fillet steak",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "green-beans",
              name: "Green beans, trimmed",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, for mash",
              quantity: 200,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "simple-spo",
              name: "Salt, pepper & olive oil pouch",
              quantity: 15,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "simple-spo",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: {
            calories: 650,
            protein: 56,
            carbs: 47,
            fat: 28,
            fiber: 8,
            sodium: 480,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
      ],
      dailyTotals: {
        calories: 2240,
        protein: 176,
        carbs: 227,
        fat: 73,
        fiber: 28,
        sodium: 1525,
      },
    },

    // ===================== Day 6 — Saturday =====================
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "oats-with-banana-and-eggs",
          name: "Oats with Banana and Eggs",
          description:
            "Rolled oats topped with sliced banana, served with two fried eggs.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 100,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "banana-sliced",
              name: "Banana, sliced",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "free-range-eggs",
              name: "Free-range eggs (x2)",
              quantity: 120,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: {
            calories: 625,
            protein: 27,
            carbs: 86,
            fat: 19,
            fiber: 11,
            sodium: 280,
          },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "korean-chicken-thigh-with-stir-fried-vegetables-and-rice",
          name: "Korean Chicken Thigh with Stir-Fried Vegetables and Rice",
          description:
            "Chicken thighs marinated in Korean sauce, stir-fried with mixed vegetables over a big bowl of white rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-thigh-sliced",
              name: "Chicken thigh, sliced",
              quantity: 250,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "broccoli",
              name: "Broccoli florets",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "carrots",
              name: "Carrots, julienned",
              quantity: 60,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "korean-marinade",
              name: "Korean marinade pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 860,
            protein: 72,
            carbs: 72,
            fat: 32,
            fiber: 6,
            sodium: 620,
          },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "lamb-leg-steak-with-garlic-herb-butter-mashed-potato-and-green-beans",
          name: "Lamb Leg Steak with Garlic Herb Butter, Mashed Potato and Green Beans",
          description:
            "Thick lamb leg steak topped with melting garlic herb butter, served with fluffy mashed white potato and steamed green beans.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "lamb-leg-steak",
              name: "Lamb leg steak",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "white-potato",
              name: "White potato, for mash",
              quantity: 220,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "green-beans",
              name: "Green beans, trimmed",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "garlic-herb-butter",
              name: "Garlic herb butter pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: {
            calories: 690,
            protein: 60,
            carbs: 42,
            fat: 32,
            fiber: 7,
            sodium: 420,
          },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [],
        },
      ],
      dailyTotals: {
        calories: 2175,
        protein: 159,
        carbs: 200,
        fat: 83,
        fiber: 24,
        sodium: 1320,
      },
    },

    // ===================== Day 7 — Sunday =====================
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "protein-pancakes-with-oats-and-banana",
          name: "Protein Pancakes with Oats and Banana",
          description:
            "Full breakfast — protein pancakes, oats, banana, honey. Sunday bulk fuel.",
          slot: "breakfast",
          ingredients: [
            {
              ingredientId: "protein-pancake-batter",
              name: "Protein pancake batter",
              quantity: 200,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "rolled-oats",
              name: "Rolled oats",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "banana-sliced",
              name: "Banana, sliced",
              quantity: 80,
              unit: "g",
              category: "breakfast",
            },
            {
              ingredientId: "raw-honey-sachet",
              name: "Raw honey sachet",
              quantity: 15,
              unit: "g",
              category: "breakfast",
            },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: {
            calories: 738,
            protein: 52,
            carbs: 105,
            fat: 14,
            fiber: 13,
            sodium: 625,
          },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [],
        },
        {
          slug: "beef-mince-tomato-curry-with-white-rice",
          name: "Beef Mince Tomato Curry with White Rice",
          description:
            "Rich tomato herb curry with beef mince, served over a generous bowl of white rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "beef-mince-15",
              name: "Beef mince (15% fat)",
              quantity: 230,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "baby-spinach",
              name: "Baby spinach",
              quantity: 60,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "tomato-herb-curry-sauce",
              name: "Tomato herb curry sauce pouch",
              quantity: 50,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 795,
            protein: 50,
            carbs: 70,
            fat: 38,
            fiber: 4,
            sodium: 480,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
        {
          slug: "chicken-breast-with-lemon-herb-couscous-and-roasted-vegetables",
          name: "Chicken Breast with Lemon Herb, Couscous and Roasted Vegetables",
          description:
            "Lemon herb dressed chicken breast with fluffy couscous and a medley of roasted zucchini and sweet peppers.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast",
              quantity: 220,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "couscous",
              name: "Couscous",
              quantity: 120,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "zucchini",
              name: "Zucchini, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "lemon-herb-dressing",
              name: "Lemon herb dressing pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 680,
            protein: 74,
            carbs: 56,
            fat: 16,
            fiber: 4,
            sodium: 380,
          },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [],
        },
      ],
      dailyTotals: {
        calories: 2213,
        protein: 176,
        carbs: 231,
        fat: 68,
        fiber: 21,
        sodium: 1485,
      },
    },
  ],
  weeklySummary: {
    days: [
      {
        day: "Monday",
        nutrition: {
          calories: 2590,
          protein: 192,
          carbs: 243,
          fat: 99,
          fiber: 28,
          sodium: 1465,
        },
      },
      {
        day: "Tuesday",
        nutrition: {
          calories: 2300,
          protein: 138,
          carbs: 230,
          fat: 92,
          fiber: 25,
          sodium: 1310,
        },
      },
      {
        day: "Wednesday",
        nutrition: {
          calories: 1873,
          protein: 181,
          carbs: 169,
          fat: 53,
          fiber: 14,
          sodium: 1330,
        },
      },
      {
        day: "Thursday",
        nutrition: {
          calories: 2123,
          protein: 155,
          carbs: 190,
          fat: 82,
          fiber: 19,
          sodium: 1235,
        },
      },
      {
        day: "Friday",
        nutrition: {
          calories: 2240,
          protein: 176,
          carbs: 227,
          fat: 73,
          fiber: 28,
          sodium: 1525,
        },
      },
      {
        day: "Saturday",
        nutrition: {
          calories: 2175,
          protein: 159,
          carbs: 200,
          fat: 83,
          fiber: 24,
          sodium: 1320,
        },
      },
      {
        day: "Sunday",
        nutrition: {
          calories: 2213,
          protein: 176,
          carbs: 231,
          fat: 68,
          fiber: 21,
          sodium: 1485,
        },
      },
    ],
    average: {
      calories: 2216,
      protein: 168,
      carbs: 213,
      fat: 79,
      fiber: 23,
      sodium: 1381,
    },
  },
};
