import type { Plan } from "@/types";

export const chickenOnlyPlan: Plan = {
  slug: "chicken-only",
  name: "Chicken Only",
  tagline: "Every cut. Every style. All chicken.",
  goal: "chicken-lovers",
  description:
    "Budget-friendly plan using every cut of chicken — breast, thigh, drumstick, wings, mince. Different style each day. Mix of sauced and sauceless meals.",
  difficulty: "beginner",
  targetCalories: 2200,
  macroSplit: { protein: 40, carbs: 40, fat: 20 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "herb-crusted-chicken-breast-white-rice-peppers",
          name: "Herb-Crusted Chicken Breast with White Rice and Peppers",
          description:
            "Chicken breast coated in dried herb and garlic seasoning, pan-fried golden. Served with fluffy white rice and roasted sweet peppers. No sauce — the herb crust carries the flavour.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 589, protein: 73, carbs: 48, fat: 13, fiber: 3, sodium: 210 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Coat chicken breast in herb and garlic seasoning",
            "Heat pan with oil, cook chicken 5-6 min per side until golden",
            "Roast peppers in same pan 3-4 min",
            "Plate rice, sliced chicken and peppers",
          ],
        },
        {
          slug: "chicken-thigh-tray-bake-root-veg-potatoes",
          name: "Chicken Thigh Tray Bake with Root Vegetables and Baby Potatoes",
          description:
            "Juicy chicken thighs roasted on a bed of carrots, baby potatoes and zucchini with rosemary and garlic. One tray, oven does the work.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "carrots", name: "Carrots, chunked", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, chunked", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["oven"],
          cookTime: 30,
          difficulty: "beginner",
          nutrition: { calories: 712, protein: 68, carbs: 40, fat: 32, fiber: 7, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Preheat oven to 200C",
            "Spread potatoes, carrots, zucchini on a tray",
            "Drizzle oil, scatter garlic and rosemary, season",
            "Place chicken thighs on top",
            "Roast 25-30 min until chicken is golden and veg is tender",
          ],
        },
      ],
      dailyTotals: { calories: 1301, protein: 141, carbs: 88, fat: 45, fiber: 10, sodium: 520 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "peri-peri-chicken-drumsticks-sweet-potato-wedges",
          name: "Peri-Peri Chicken Drumsticks with Sweet Potato Wedges and Slaw",
          description:
            "Chicken drumsticks coated in peri-peri marinade, air-fried crispy. Served with sweet potato wedges. Add a simple slaw for crunch.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-drumstick", name: "Chicken drumsticks (x3)", quantity: 240, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cut into wedges", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 558, protein: 70, carbs: 34, fat: 16, fiber: 4, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat drumsticks in peri-peri marinade",
            "Cut sweet potato into wedges",
            "Air fry drumsticks and wedges at 200C for 18-20 min",
            "Alternatively, oven roast at 200C for 25 min",
            "Plate with optional simple slaw",
          ],
        },
        {
          slug: "chicken-mince-teriyaki-noodles",
          name: "Chicken Mince Stir-Fry with Teriyaki, Vegetables and Noodles",
          description:
            "Chicken mince stir-fried in teriyaki glaze with broccoli and carrots over rice noodles.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-mince", name: "Chicken mince", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "carrots", name: "Carrots, julienned", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "rice-noodles", name: "Rice noodles", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "teriyaki", name: "Teriyaki glaze pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 520, protein: 39, carbs: 52, fat: 18, fiber: 4, sodium: 535 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook rice noodles per packet instructions",
            "Heat pan to high, add chicken mince and break up",
            "Cook 4-5 min until browned",
            "Add broccoli and carrots, stir-fry 2-3 min",
            "Add teriyaki glaze, toss through noodles",
          ],
        },
      ],
      dailyTotals: { calories: 1078, protein: 109, carbs: 86, fat: 34, fiber: 8, sodium: 915 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "smoky-bbq-chicken-wings-corn",
          name: "Smoky BBQ Chicken Wings with Corn and Garden Salad",
          description:
            "Chicken wings coated in smoky BBQ, air-fried until crispy. Served with charred corn. Add a garden salad for a complete plate.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-wings", name: "Chicken wings", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 610, protein: 79, carbs: 27, fat: 22, fiber: 3, sodium: 440 },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat wings in smoky BBQ marinade",
            "Air fry at 200C for 18-20 min, turning halfway",
            "Char corn in a dry pan or air fryer 4-5 min",
            "Plate wings with corn and optional garden salad",
          ],
        },
        {
          slug: "chicken-breast-white-rice-steamed-veg",
          name: "Chicken Breast with White Rice and Steamed Vegetables",
          description:
            "Simple grilled chicken breast with salt and pepper. White rice and steamed broccoli and green beans. Clean, simple, effective.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 580, protein: 73, carbs: 47, fat: 12, fiber: 5, sodium: 230 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Steam broccoli and green beans 4 min",
            "Plate rice, chicken and steamed vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1190, protein: 152, carbs: 74, fat: 34, fiber: 8, sodium: 670 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "shawarma-chicken-thigh-couscous-roasted-veg",
          name: "Shawarma Chicken Thigh with Couscous and Roasted Vegetables",
          description:
            "Chicken thighs rubbed in shawarma spice blend, pan-seared, served with fluffy couscous and roasted zucchini and peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice blend pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 668, protein: 63, carbs: 42, fat: 28, fiber: 3, sodium: 380 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub chicken thighs with shawarma spice and olive oil",
            "Pan-sear 5-6 min per side until cooked through",
            "Prepare couscous with boiling water per instructions",
            "Roast zucchini and peppers in same pan 3-4 min",
            "Fluff couscous, plate with chicken and roasted vegetables",
          ],
        },
        {
          slug: "chicken-breast-coconut-curry-brown-rice",
          name: "Chicken Breast with Coconut Curry and Brown Rice",
          description:
            "Diced chicken breast in a mild coconut curry sauce with spinach, served over brown rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, diced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 618, protein: 72, carbs: 42, fat: 16, fiber: 4, sodium: 360 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan, cook diced chicken 4-5 min until browned",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over brown rice",
          ],
        },
      ],
      dailyTotals: { calories: 1286, protein: 135, carbs: 84, fat: 44, fiber: 7, sodium: 740 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "chicken-breast-med-herbs-pasta",
          name: "Chicken Breast with Mediterranean Herbs and Pasta",
          description:
            "Mediterranean herb-marinated chicken breast sliced over penne with roasted peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 598, protein: 68, carbs: 44, fat: 16, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Marinate chicken in Mediterranean herbs",
            "Pan-fry chicken 5-6 min per side",
            "Roast peppers in same pan 3-4 min",
            "Slice chicken, toss with pasta and peppers",
          ],
        },
        {
          slug: "chicken-thigh-sweet-potato-green-beans",
          name: "Chicken Thigh with Sweet Potato and Green Beans",
          description:
            "Pan-fried chicken thighs, skin-on for flavour, seasoned simply. Sweet potato mash and steamed green beans.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, bone-in skin-on (x2)", quantity: 260, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, for mash", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 680, protein: 69, carbs: 38, fat: 28, fiber: 6, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato until soft, mash with salt and pepper",
            "Heat pan, cook chicken thighs skin-side down 6-7 min until crispy",
            "Flip, cook 5-6 min more until cooked through",
            "Steam green beans 4 min",
            "Plate mash, chicken and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1278, protein: 137, carbs: 82, fat: 44, fiber: 9, sodium: 620 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "chicken-drumsticks-chimichurri-baby-potatoes",
          name: "Chicken Drumsticks with Chimichurri and Baby Potatoes",
          description:
            "Roasted chicken drumsticks with fresh chimichurri drizzled over. Halved baby potatoes roasted alongside.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-drumstick", name: "Chicken drumsticks (x3)", quantity: 240, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 160, unit: "g", category: "carb" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["oven", "air-fryer"],
          cookTime: 25,
          difficulty: "beginner",
          nutrition: { calories: 588, protein: 71, carbs: 30, fat: 22, fiber: 4, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Preheat oven to 200C",
            "Arrange drumsticks and halved baby potatoes on tray",
            "Season with salt, pepper and oil",
            "Roast 25 min until golden and cooked through",
            "Drizzle chimichurri over drumsticks before serving",
          ],
        },
        {
          slug: "chicken-mince-tomato-curry-white-rice",
          name: "Chicken Mince Tomato Curry with White Rice",
          description:
            "Chicken mince simmered in a rich tomato herb curry sauce with baby spinach, served over white rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-mince", name: "Chicken mince", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "white-rice", name: "White rice", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 553, protein: 40, carbs: 58, fat: 18, fiber: 4, sodium: 390 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan, cook chicken mince 4-5 min until browned",
            "Pour in tomato curry sauce, simmer 8-10 min",
            "Stir in spinach until wilted",
            "Serve over rice",
          ],
        },
      ],
      dailyTotals: { calories: 1141, protein: 111, carbs: 88, fat: 40, fiber: 8, sodium: 700 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "chicken-breast-salad-lemon-herb",
          name: "Chicken Breast Salad with Lemon Herb",
          description:
            "Sliced grilled chicken over a large mixed salad with cherry tomatoes, cucumber and lemon herb dressing. Light Sunday lunch.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 70, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "cucumber", name: "Cucumber, sliced", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 520, protein: 72, carbs: 27, fat: 15, fiber: 5, sodium: 355 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 12 min",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Arrange salad leaves, tomatoes and cucumber on plate",
            "Slice chicken over salad, add sweet potato",
            "Drizzle lemon herb dressing",
          ],
        },
        {
          slug: "smoky-bbq-chicken-thigh-pasta-corn",
          name: "Smoky BBQ Chicken Thigh with Pasta and Corn",
          description:
            "Smoky BBQ-glazed chicken thighs with penne pasta and charred corn.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 240, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 752, protein: 68, carbs: 60, fat: 28, fiber: 4, sodium: 460 },
          allergens: ["mustard", "gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Coat chicken thighs in smoky BBQ marinade",
            "Pan-fry or oven bake at 200C for 18-20 min",
            "Char corn in a dry pan 3-4 min",
            "Slice chicken, toss with pasta and corn",
          ],
        },
      ],
      dailyTotals: { calories: 1272, protein: 140, carbs: 87, fat: 43, fiber: 9, sodium: 815 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1301, protein: 141, carbs: 88, fat: 45, fiber: 10, sodium: 520 } },
      { day: "Tuesday", nutrition: { calories: 1078, protein: 109, carbs: 86, fat: 34, fiber: 8, sodium: 915 } },
      { day: "Wednesday", nutrition: { calories: 1190, protein: 152, carbs: 74, fat: 34, fiber: 8, sodium: 670 } },
      { day: "Thursday", nutrition: { calories: 1286, protein: 135, carbs: 84, fat: 44, fiber: 7, sodium: 740 } },
      { day: "Friday", nutrition: { calories: 1278, protein: 137, carbs: 82, fat: 44, fiber: 9, sodium: 620 } },
      { day: "Saturday", nutrition: { calories: 1141, protein: 111, carbs: 88, fat: 40, fiber: 8, sodium: 700 } },
      { day: "Sunday", nutrition: { calories: 1272, protein: 140, carbs: 87, fat: 43, fiber: 9, sodium: 815 } },
    ],
    average: { calories: 1221, protein: 132, carbs: 84, fat: 41, fiber: 8, sodium: 711 },
  },
};
