import type { Plan } from "@/types";

export const globalFlavourPlan: Plan = {
  slug: "global-flavour",
  name: "Monthly Global Flavour",
  tagline: "Travel the world through food. New flavours every month.",
  goal: "global",
  description:
    "Changes every month. Month 1: Flavours of the Levant (Middle Eastern). Unique spice packs and marinades included. Available as standalone plan or add-on. Premium members get this free.",
  difficulty: "intermediate",
  targetCalories: 2300,
  macroSplit: { protein: 30, carbs: 40, fat: 30 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "gf-shawarma-chicken-thigh-couscous-roasted-veg",
          name: "Shawarma Chicken Thigh with Couscous, Roasted Vegetables and Garden Salad",
          description:
            "Shawarma-spiced chicken thighs with fluffy couscous, roasted zucchini, peppers and cherry tomatoes. Add a garden salad for the full Levantine experience.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 678, protein: 62, carbs: 42, fat: 30, fiber: 4, sodium: 380 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub chicken thighs with shawarma spice and olive oil",
            "Pan-sear 5-6 min per side until cooked through",
            "Prepare couscous with boiling water",
            "Roast zucchini, peppers and tomatoes 10 min at 200C",
            "Fluff couscous, plate with chicken and roasted vegetables",
          ],
        },
        {
          slug: "gf-beef-kofta-tomato-sauce-white-rice",
          name: "Beef Kofta in Tomato Sauce with White Rice",
          description:
            "Handmade beef kofta simmered in rich tomato herb curry sauce, served over white rice with a side of baby spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-kofta", name: "Beef kofta (pre-formed)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 628, protein: 46, carbs: 52, fat: 28, fiber: 3, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook rice per instructions",
            "Heat pan to medium-high, cook kofta 3-4 min per side until browned all over",
            "Pour tomato curry sauce over kofta, reduce heat",
            "Simmer 8-10 min until kofta cooked through and sauce thickens",
            "Stir spinach through sauce in last minute",
            "Serve over rice",
          ],
        },
      ],
      dailyTotals: { calories: 1306, protein: 108, carbs: 94, fat: 58, fiber: 7, sodium: 760 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "gf-lamb-kofta-shawarma-couscous-eggplant",
          name: "Lamb Kofta with Shawarma Spice, Couscous and Roasted Eggplant",
          description: "Lamb kofta with shawarma spice, fluffy couscous and roasted eggplant with cherry tomatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-kofta", name: "Lamb kofta (pre-formed)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "eggplant", name: "Eggplant, cubed", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "oven"],
          cookTime: 22,
          difficulty: "intermediate",
          nutrition: { calories: 698, protein: 42, carbs: 44, fat: 42, fiber: 5, sodium: 380 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub kofta with shawarma spice",
            "Pan-sear kofta 3-4 min per side until browned",
            "Roast eggplant and tomatoes at 200C for 12 min with olive oil",
            "Prepare couscous with boiling water",
            "Plate couscous with kofta and roasted vegetables",
          ],
        },
        {
          slug: "gf-shawarma-lamb-leg-steak-brown-rice-roasted-veg",
          name: "Shawarma Lamb Leg Steak with Brown Rice and Roasted Vegetables",
          description: "Shawarma-spiced lamb leg steak with brown rice and roasted sweet peppers and zucchini.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 592, protein: 62, carbs: 38, fat: 22, fiber: 4, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Rub lamb leg steak with shawarma spice and olive oil",
            "Pan-sear 4 min per side, rest 3 min",
            "Roast peppers and zucchini in same pan 3-4 min",
            "Plate rice, sliced lamb and roasted vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1290, protein: 104, carbs: 82, fat: 64, fiber: 9, sodium: 690 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "gf-chicken-breast-lemon-herb-baby-potatoes-salad",
          name: "Chicken Breast with Lemon Herb, Baby Potatoes and Mixed Salad",
          description: "Grilled chicken breast with lemon herb dressing, baby potatoes and a fresh mixed salad. Light Levantine lunch.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 508, protein: 65, carbs: 28, fat: 17, fiber: 4, sodium: 340 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Arrange salad and tomatoes on plate",
            "Slice chicken over salad, add potatoes",
            "Drizzle lemon herb dressing",
          ],
        },
        {
          slug: "gf-beef-kofta-coconut-curry-brown-rice",
          name: "Beef Kofta with Coconut Curry and Brown Rice",
          description:
            "Beef kofta in a mild coconut curry sauce — a Middle Eastern and South Asian fusion. Served over brown rice with spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-kofta", name: "Beef kofta (pre-formed)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 658, protein: 48, carbs: 46, fat: 32, fiber: 4, sodium: 360 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan, brown kofta 3-4 min per side",
            "Pour in coconut curry sauce, simmer 8-10 min",
            "Stir in spinach in last minute",
            "Serve over brown rice",
          ],
        },
      ],
      dailyTotals: { calories: 1166, protein: 113, carbs: 74, fat: 49, fiber: 8, sodium: 700 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "gf-shawarma-chicken-thigh-white-rice-roasted-veg",
          name: "Shawarma Chicken Thigh with White Rice and Roasted Vegetables",
          description: "Shawarma-spiced chicken thighs with white rice and roasted zucchini and peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 658, protein: 60, carbs: 50, fat: 28, fiber: 3, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub chicken thighs with shawarma spice and olive oil",
            "Pan-sear 5-6 min per side until cooked through",
            "Cook white rice per packet instructions",
            "Roast zucchini and peppers in same pan 3-4 min",
            "Plate rice, chicken and roasted vegetables",
          ],
        },
        {
          slug: "gf-beef-kofta-tomato-sauce-couscous",
          name: "Beef Kofta in Tomato Sauce with Couscous",
          description: "Beef kofta simmered in tomato herb curry sauce, served over fluffy couscous with spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-kofta", name: "Beef kofta (pre-formed)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 648, protein: 46, carbs: 48, fat: 32, fiber: 4, sodium: 380 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Prepare couscous with boiling water",
            "Heat pan, cook kofta 3-4 min per side until browned",
            "Pour tomato curry sauce over kofta, simmer 8-10 min",
            "Stir spinach through in last minute",
            "Serve over couscous",
          ],
        },
      ],
      dailyTotals: { calories: 1306, protein: 106, carbs: 98, fat: 60, fiber: 7, sodium: 760 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "gf-lamb-leg-steak-lemon-herb-baby-potatoes",
          name: "Lamb Leg Steak with Lemon Herb and Baby Potatoes",
          description: "Pan-seared lamb leg steak with lemon herb dressing and baby potatoes. Simple, clean Levantine plate.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 160, unit: "g", category: "carb" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 560, protein: 60, carbs: 32, fat: 22, fiber: 5, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with olive oil, season lamb",
            "Sear 4 min per side, rest 3 min",
            "Arrange salad on plate",
            "Slice lamb, plate with potatoes and salad, drizzle lemon herb",
          ],
        },
        {
          slug: "gf-chicken-breast-med-herbs-roasted-veg-couscous",
          name: "Chicken Breast with Mediterranean Herbs and Roasted Vegetables",
          description: "Mediterranean herb chicken breast with roasted peppers, zucchini and couscous.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 540, protein: 66, carbs: 36, fat: 14, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Marinate chicken in Mediterranean herbs",
            "Pan-fry 5-6 min per side",
            "Prepare couscous with boiling water",
            "Roast peppers and zucchini in same pan 3-4 min",
            "Fluff couscous, plate with sliced chicken and roasted vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1100, protein: 126, carbs: 68, fat: 36, fiber: 8, sodium: 620 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "gf-lamb-kofta-shawarma-brown-rice-spinach",
          name: "Lamb Kofta with Shawarma Spice and Brown Rice",
          description: "Shawarma-spiced lamb kofta with brown rice and wilted spinach.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-kofta", name: "Lamb kofta (pre-formed)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 680, protein: 44, carbs: 42, fat: 40, fiber: 4, sodium: 360 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Rub kofta with shawarma spice",
            "Pan-sear 3-4 min per side until cooked through",
            "Wilt spinach in same pan 1 min",
            "Plate rice, kofta and wilted spinach",
          ],
        },
        {
          slug: "gf-lamb-chops-roasted-peppers-lemon",
          name: "Grilled Lamb Chops with Roasted Peppers",
          description: "Simple grilled lamb chops with salt, pepper and lemon, served with roasted peppers and baby potatoes.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 660, protein: 56, carbs: 30, fat: 38, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season lamb chops with salt and pepper",
            "Sear 3 min per side, rest 2 min",
            "Roast peppers in same pan 3-4 min",
            "Squeeze lemon over lamb, plate with potatoes and peppers",
          ],
        },
      ],
      dailyTotals: { calories: 1340, protein: 100, carbs: 72, fat: 78, fiber: 9, sodium: 620 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "gf-shawarma-lamb-leg-steak-couscous-eggplant",
          name: "Shawarma Lamb Leg Steak with Couscous and Roasted Eggplant",
          description: "Shawarma-spiced lamb leg steak with couscous and roasted eggplant. Sunday Levantine feast.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "eggplant", name: "Eggplant, cubed", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan"],
          cookTime: 22,
          difficulty: "intermediate",
          nutrition: { calories: 620, protein: 62, carbs: 38, fat: 24, fiber: 5, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub lamb leg steak with shawarma spice and olive oil",
            "Pan-sear 4 min per side, rest 3 min",
            "Roast eggplant and tomatoes at 200C for 12 min",
            "Prepare couscous with boiling water",
            "Plate couscous, sliced lamb and roasted vegetables",
          ],
        },
        {
          slug: "gf-chicken-thigh-coconut-curry-white-rice-spinach",
          name: "Chicken Thigh Coconut Curry with White Rice",
          description: "Diced chicken thigh in coconut curry sauce with spinach over white rice. Levantine-South Asian fusion.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, diced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 648, protein: 56, carbs: 50, fat: 28, fiber: 3, sodium: 360 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan, cook diced chicken thigh 4-5 min",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over white rice",
          ],
        },
      ],
      dailyTotals: { calories: 1268, protein: 118, carbs: 88, fat: 52, fiber: 8, sodium: 670 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1306, protein: 108, carbs: 94, fat: 58, fiber: 7, sodium: 760 } },
      { day: "Tuesday", nutrition: { calories: 1290, protein: 104, carbs: 82, fat: 64, fiber: 9, sodium: 690 } },
      { day: "Wednesday", nutrition: { calories: 1166, protein: 113, carbs: 74, fat: 49, fiber: 8, sodium: 700 } },
      { day: "Thursday", nutrition: { calories: 1306, protein: 106, carbs: 98, fat: 60, fiber: 7, sodium: 760 } },
      { day: "Friday", nutrition: { calories: 1100, protein: 126, carbs: 68, fat: 36, fiber: 8, sodium: 620 } },
      { day: "Saturday", nutrition: { calories: 1340, protein: 100, carbs: 72, fat: 78, fiber: 9, sodium: 620 } },
      { day: "Sunday", nutrition: { calories: 1268, protein: 118, carbs: 88, fat: 52, fiber: 8, sodium: 670 } },
    ],
    average: { calories: 1254, protein: 111, carbs: 82, fat: 57, fiber: 8, sodium: 689 },
  },
};
