import type { Plan } from "@/types";

export const leanMachinePlan: Plan = {
  slug: "the-lean-machine",
  name: "The Lean Machine",
  tagline: "Cut fat, keep muscle. High protein, controlled carbs.",
  goal: "fat-loss",
  description:
    "Designed for fat loss and cutting. High protein meals with controlled carbs and healthy fats. Two meals per day (lunch + dinner) averaging ~1,800 cal/day when combined with your own breakfast. Every meal is portioned, prepped, and ready to cook in under 20 minutes.",
  difficulty: "beginner",
  targetCalories: 1800,
  macroSplit: { protein: 40, carbs: 35, fat: 25 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  featured: true,
  days: [
    // Day 1 — Monday
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "grilled-chicken-breast-with-charred-broccoli-and-sweet-potato",
          name: "Grilled Chicken Breast with Charred Broccoli and Sweet Potato",
          description:
            "Butterflied chicken breast rubbed with simple salt, pepper and olive oil, pan-seared until golden. Served with charred broccoli florets and roasted sweet potato wedges.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "broccoli",
              name: "Broccoli florets",
              quantity: 150,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, cut into wedges",
              quantity: 120,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "simple-spo",
              name: "Salt, Pepper & Olive Oil pouch",
              quantity: 15,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "simple-spo",
          cookingMethods: ["pan", "air-fryer"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 502,
            protein: 67,
            carbs: 35,
            fat: 18,
            fiber: 8,
            sodium: 510,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to medium-high with oil from sauce pouch",
            "Season chicken with salt and pepper from pouch",
            "Cook chicken 5-6 min per side until golden and cooked through",
            "While chicken cooks, spread sweet potato wedges on a tray, drizzle remaining oil, air fry at 200C for 15 min OR pan alongside chicken",
            "Add broccoli to pan in last 5 min, char on high heat",
            "Rest chicken 2 min, slice, serve over vegetables",
          ],
        },
        {
          slug: "lean-beef-mince-stir-fry-with-green-beans-and-brown-rice",
          name: "Lean Beef Mince Stir-Fry with Green Beans and Brown Rice",
          description:
            "Extra-lean beef mince flash-fried with teriyaki glaze, tossed with crisp green beans over a bed of brown rice.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-mince-lean",
              name: "Extra lean beef mince (5%)",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "green-beans",
              name: "Green beans, trimmed",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "brown-rice",
              name: "Brown rice",
              quantity: 100,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "teriyaki",
              name: "Teriyaki glaze pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: {
            calories: 458,
            protein: 42,
            carbs: 38,
            fat: 12,
            fiber: 5,
            sodium: 555,
          },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions (or microwave rice if provided)",
            "Heat pan or wok to high",
            "Add beef mince, break apart, cook 4-5 min until browned",
            "Add green beans, stir-fry 3 min until bright and slightly charred",
            "Pour teriyaki glaze over, toss to coat, cook 1 min",
            "Serve over brown rice",
          ],
        },
      ],
      dailyTotals: {
        calories: 960,
        protein: 109,
        carbs: 73,
        fat: 30,
        fiber: 13,
        sodium: 1065,
      },
    },

    // Day 2 — Tuesday
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "lamb-leg-steak-with-spinach-and-baby-potatoes",
          name: "Lamb Leg Steak with Spinach and Baby Potatoes",
          description:
            "Pan-seared lamb leg steak with lemon herb dressing, served over wilted baby spinach with roasted baby potatoes.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "lamb-leg-steak",
              name: "Lamb leg steak",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "spinach",
              name: "Baby spinach",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "baby-potatoes",
              name: "Baby potatoes, halved",
              quantity: 150,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "lemon-herb",
              name: "Lemon herb dressing pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 508,
            protein: 54,
            carbs: 29,
            fat: 20,
            fiber: 5,
            sodium: 350,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil or microwave baby potatoes until tender (10 min)",
            "Heat pan to medium-high, cook lamb leg steak 4-5 min per side for medium",
            "Rest lamb 3 min",
            "Wilt spinach in same pan with residual heat (1 min)",
            "Plate potatoes and spinach, slice lamb on top",
            "Drizzle lemon herb dressing",
          ],
        },
        {
          slug: "chicken-breast-with-chimichurri-and-asparagus",
          name: "Chicken Breast with Chimichurri and Asparagus",
          description:
            "Grilled chicken breast drizzled with fresh chimichurri, served with grilled asparagus and a small sweet potato.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "asparagus",
              name: "Asparagus spears",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, sliced",
              quantity: 100,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "chimichurri",
              name: "Chimichurri pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan", "air-fryer"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 494,
            protein: 66,
            carbs: 25,
            fat: 16,
            fiber: 6,
            sodium: 385,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Slice sweet potato into rounds, pan-fry or air fry at 200C for 12 min",
            "Cook chicken breast in pan 5-6 min per side",
            "Add asparagus to pan in last 4 min, cook until slightly charred",
            "Slice chicken, plate with asparagus and sweet potato",
            "Spoon chimichurri over chicken",
          ],
        },
      ],
      dailyTotals: {
        calories: 1002,
        protein: 120,
        carbs: 54,
        fat: 36,
        fiber: 11,
        sodium: 735,
      },
    },

    // Day 3 — Wednesday
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "beef-rump-steak-with-roasted-vegetables-and-brown-rice",
          name: "Beef Rump Steak with Roasted Vegetables and Brown Rice",
          description:
            "Seared beef rump rubbed with Mediterranean herbs, served with roasted sweet peppers, zucchini and a small portion of brown rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "beef-rump",
              name: "Beef rump steak",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "zucchini",
              name: "Zucchini, sliced",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "brown-rice",
              name: "Brown rice",
              quantity: 80,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "med-herb",
              name: "Mediterranean herb marinade pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 530,
            protein: 55,
            carbs: 31,
            fat: 22,
            fiber: 5,
            sodium: 340,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per instructions",
            "Rub rump steak with half the Mediterranean herb marinade",
            "Heat pan to high, sear steak 3-4 min per side for medium",
            "Rest steak, add peppers and zucchini to same pan with remaining marinade",
            "Cook vegetables 4-5 min until softened and slightly charred",
            "Slice steak, serve over rice with vegetables",
          ],
        },
        {
          slug: "peri-peri-chicken-thigh-with-spinach-and-sweet-potato",
          name: "Peri-Peri Chicken Thigh with Spinach and Sweet Potato",
          description:
            "Marinated peri-peri chicken thigh, air-fried until crispy on the outside, served with wilted spinach and roasted sweet potato cubes.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "chicken-thigh",
              name: "Chicken thigh (skin off, boneless)",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "spinach",
              name: "Baby spinach",
              quantity: 80,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, cubed",
              quantity: 100,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "peri-peri",
              name: "Peri-peri marinade pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 478,
            protein: 50,
            carbs: 24,
            fat: 21,
            fiber: 4,
            sodium: 365,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Toss chicken thigh in peri-peri marinade pouch",
            "Air fryer: 200C, 15 min, flip halfway. Oven: 200C, 20 min.",
            "Toss sweet potato cubes with a drizzle of oil, cook alongside chicken in air fryer/oven",
            "Wilt spinach in pan or microwave for 1 min",
            "Plate sweet potato and spinach, top with peri-peri chicken",
          ],
        },
      ],
      dailyTotals: {
        calories: 1008,
        protein: 105,
        carbs: 55,
        fat: 43,
        fiber: 9,
        sodium: 705,
      },
    },

    // Day 4 — Thursday
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "teriyaki-chicken-stir-fry-with-broccoli-and-white-rice",
          name: "Teriyaki Chicken Stir-Fry with Broccoli and White Rice",
          description:
            "Sliced chicken breast stir-fried with teriyaki glaze and broccoli florets, served over steamed white rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast, sliced",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "broccoli",
              name: "Broccoli florets",
              quantity: 130,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 90,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "teriyaki",
              name: "Teriyaki glaze pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: {
            calories: 492,
            protein: 68,
            carbs: 37,
            fat: 10,
            fiber: 4,
            sodium: 565,
          },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per instructions",
            "Heat pan/wok to high",
            "Cook chicken strips 4-5 min until white throughout",
            "Add broccoli, stir-fry 3 min",
            "Add teriyaki glaze, toss 1 min",
            "Serve over rice",
          ],
        },
        {
          slug: "lamb-chops-with-simple-salt-and-pepper-green-beans-and-baby-potatoes",
          name: "Lamb Chops with Simple Salt & Pepper, Green Beans and Baby Potatoes",
          description:
            "Two lamb chops seasoned simply with salt, pepper and olive oil, pan-seared, served with steamed green beans and boiled baby potatoes.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "lamb-chops",
              name: "Lamb chops (x2)",
              quantity: 160,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "green-beans",
              name: "Green beans, trimmed",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "baby-potatoes",
              name: "Baby potatoes, halved",
              quantity: 130,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "simple-spo",
              name: "Salt, pepper & olive oil pouch",
              quantity: 15,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "simple-spo",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 520,
            protein: 44,
            carbs: 26,
            fat: 29,
            fiber: 6,
            sodium: 520,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes until tender (10 min)",
            "Season lamb chops with salt and pepper from pouch",
            "Heat pan to high with oil from pouch, sear chops 3-4 min per side",
            "Steam or boil green beans 4 min until bright green",
            "Rest lamb 2 min, serve with potatoes and beans",
          ],
        },
      ],
      dailyTotals: {
        calories: 1012,
        protein: 112,
        carbs: 63,
        fat: 39,
        fiber: 10,
        sodium: 1085,
      },
    },

    // Day 5 — Friday
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "smoky-bbq-chicken-drumsticks-with-corn-and-mixed-salad",
          name: "Smoky BBQ Chicken Drumsticks with Corn and Mixed Salad",
          description:
            "Chicken drumsticks coated in smoky BBQ marinade, air-fried until crispy, served with charred corn and a fresh mixed salad.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-drumsticks",
              name: "Chicken drumsticks (x3)",
              quantity: 210,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "corn",
              name: "Sweet corn, cut",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "mixed-salad",
              name: "Mixed salad leaves",
              quantity: 60,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "smoky-bbq",
              name: "Smoky BBQ marinade pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 468,
            protein: 63,
            carbs: 23,
            fat: 15,
            fiber: 4,
            sodium: 435,
          },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat drumsticks in BBQ marinade",
            "Air fryer: 190C, 18-20 min, turning halfway. Oven: 200C, 25 min.",
            "Char corn in pan or alongside in air fryer last 5 min",
            "Plate salad leaves, top with corn and drumsticks",
          ],
        },
        {
          slug: "beef-sirloin-with-garlic-herb-butter-asparagus-and-sweet-potato",
          name: "Beef Sirloin with Garlic Herb Butter, Asparagus and Sweet Potato",
          description:
            "Pan-seared sirloin steak topped with a melting disc of garlic herb butter, served with grilled asparagus and sweet potato wedges.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "beef-sirloin",
              name: "Beef sirloin steak",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "asparagus",
              name: "Asparagus spears",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, cut into wedges",
              quantity: 110,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "garlic-herb-butter",
              name: "Garlic herb butter pouch",
              quantity: 30,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 558,
            protein: 52,
            carbs: 24,
            fat: 30,
            fiber: 5,
            sodium: 380,
          },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Cook sweet potato wedges in air fryer/oven at 200C for 15 min, or pan-fry",
            "Heat pan to high, cook sirloin 3-4 min per side for medium",
            "Place garlic herb butter disc on top of steak while resting (3 min)",
            "Grill asparagus in same pan 3-4 min",
            "Plate with melting butter over steak",
          ],
        },
      ],
      dailyTotals: {
        calories: 1026,
        protein: 115,
        carbs: 47,
        fat: 45,
        fiber: 9,
        sodium: 815,
      },
    },

    // Day 6 — Saturday
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "korean-beef-strips-with-broccoli-and-white-rice",
          name: "Korean Beef Strips with Broccoli and White Rice",
          description:
            "Thin-sliced beef strips marinated in Korean-inspired gochugaru and pear marinade, stir-fried with broccoli over white rice.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "beef-rump",
              name: "Beef rump, thin-sliced strips",
              quantity: 180,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "broccoli",
              name: "Broccoli florets",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "white-rice",
              name: "White rice",
              quantity: 90,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "korean",
              name: "Korean marinade pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: {
            calories: 510,
            protein: 55,
            carbs: 35,
            fat: 18,
            fiber: 4,
            sodium: 565,
          },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook rice per instructions",
            "Heat pan/wok to high",
            "Stir-fry beef strips 3-4 min until browned",
            "Add broccoli, cook 3 min",
            "Pour Korean marinade over, toss 1 min",
            "Serve over rice",
          ],
        },
        {
          slug: "chicken-breast-with-mediterranean-herbs-roasted-peppers-and-couscous",
          name: "Chicken Breast with Mediterranean Herbs, Roasted Peppers and Couscous",
          description:
            "Chicken breast marinated in Mediterranean herbs, pan-cooked, served with roasted sweet peppers and fluffy couscous.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "sweet-peppers",
              name: "Sweet peppers, sliced",
              quantity: 100,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "couscous",
              name: "Couscous",
              quantity: 80,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "med-herb",
              name: "Mediterranean herb marinade pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 498,
            protein: 67,
            carbs: 27,
            fat: 15,
            fiber: 3,
            sodium: 350,
          },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub chicken with half the Mediterranean herb marinade",
            "Heat pan, cook chicken 5-6 min per side",
            "Cook peppers in same pan with remaining marinade 4 min",
            "Prepare couscous: pour boiling water over, cover, stand 5 min, fluff",
            "Slice chicken, serve over couscous with peppers",
          ],
        },
      ],
      dailyTotals: {
        calories: 1008,
        protein: 122,
        carbs: 62,
        fat: 33,
        fiber: 7,
        sodium: 915,
      },
    },

    // Day 7 — Sunday
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "coconut-chicken-curry-with-brown-rice",
          name: "Coconut Chicken Curry with Brown Rice",
          description:
            "Tender chicken breast simmered in a mild coconut curry sauce with spinach, served over brown rice. A warming, satisfying meal that stays within macros.",
          slot: "lunch",
          ingredients: [
            {
              ingredientId: "chicken-breast",
              name: "Chicken breast, diced",
              quantity: 200,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "spinach",
              name: "Baby spinach",
              quantity: 60,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "brown-rice",
              name: "Brown rice",
              quantity: 90,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "coconut-curry",
              name: "Coconut curry sauce pouch",
              quantity: 50,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: {
            calories: 528,
            protein: 66,
            carbs: 30,
            fat: 18,
            fiber: 5,
            sodium: 350,
          },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per instructions",
            "Heat pan to medium-high, cook diced chicken 5-6 min until browned",
            "Pour coconut curry sauce over chicken, reduce heat to medium",
            "Simmer 5 min until sauce thickens slightly",
            "Stir in spinach, cook 1 min until wilted",
            "Serve over brown rice",
          ],
        },
        {
          slug: "lamb-leg-steak-with-chimichurri-green-beans-and-sweet-potato",
          name: "Lamb Leg Steak with Chimichurri, Green Beans and Sweet Potato",
          description:
            "Pan-seared lamb leg steak with vibrant chimichurri, served with crisp green beans and roasted sweet potato.",
          slot: "dinner",
          ingredients: [
            {
              ingredientId: "lamb-leg-steak",
              name: "Lamb leg steak",
              quantity: 170,
              unit: "g",
              category: "protein",
            },
            {
              ingredientId: "green-beans",
              name: "Green beans, trimmed",
              quantity: 120,
              unit: "g",
              category: "vegetable",
            },
            {
              ingredientId: "sweet-potato",
              name: "Sweet potato, cubed",
              quantity: 100,
              unit: "g",
              category: "carb",
            },
            {
              ingredientId: "chimichurri",
              name: "Chimichurri pouch",
              quantity: 25,
              unit: "g",
              category: "sauce",
            },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: {
            calories: 480,
            protein: 51,
            carbs: 25,
            fat: 21,
            fiber: 6,
            sodium: 300,
          },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast or air fry sweet potato cubes at 200C for 15 min",
            "Heat pan to high, cook lamb leg steak 4-5 min per side for medium",
            "Rest lamb 3 min",
            "Steam or pan-fry green beans 4 min",
            "Slice lamb, plate with sweet potato and beans",
            "Spoon chimichurri over lamb",
          ],
        },
      ],
      dailyTotals: {
        calories: 1008,
        protein: 117,
        carbs: 55,
        fat: 39,
        fiber: 11,
        sodium: 650,
      },
    },
  ],
  weeklySummary: {
    days: [
      {
        day: "Mon",
        nutrition: {
          calories: 960,
          protein: 109,
          carbs: 73,
          fat: 30,
          fiber: 13,
          sodium: 1065,
        },
      },
      {
        day: "Tue",
        nutrition: {
          calories: 1002,
          protein: 120,
          carbs: 54,
          fat: 36,
          fiber: 11,
          sodium: 735,
        },
      },
      {
        day: "Wed",
        nutrition: {
          calories: 1008,
          protein: 105,
          carbs: 55,
          fat: 43,
          fiber: 9,
          sodium: 705,
        },
      },
      {
        day: "Thu",
        nutrition: {
          calories: 1012,
          protein: 112,
          carbs: 63,
          fat: 39,
          fiber: 10,
          sodium: 1085,
        },
      },
      {
        day: "Fri",
        nutrition: {
          calories: 1026,
          protein: 115,
          carbs: 47,
          fat: 45,
          fiber: 9,
          sodium: 815,
        },
      },
      {
        day: "Sat",
        nutrition: {
          calories: 1008,
          protein: 122,
          carbs: 62,
          fat: 33,
          fiber: 7,
          sodium: 915,
        },
      },
      {
        day: "Sun",
        nutrition: {
          calories: 1008,
          protein: 117,
          carbs: 55,
          fat: 39,
          fiber: 11,
          sodium: 650,
        },
      },
    ],
    average: {
      calories: 1003,
      protein: 114,
      carbs: 58,
      fat: 38,
      fiber: 10,
      sodium: 853,
    },
  },
};
