import type { Plan } from "@/types";

export const pureProteinPlan: Plan = {
  slug: "pure-protein",
  name: "Pure Protein",
  tagline: "Maximum protein per meal. Let the meat speak.",
  goal: "high-protein",
  description:
    "Double protein plates, sauceless steaks, and massive chicken portions. Many meals are sauceless — just well-seasoned quality protein with simple vegetables. Optional side sauces (mushroom, pepper, gravy) recommended as add-ons.",
  difficulty: "beginner",
  targetCalories: 2400,
  macroSplit: { protein: 50, carbs: 25, fat: 25 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "double-chicken-breast-broccoli-spinach",
          name: "Double Chicken Breast with Steamed Broccoli and Spinach",
          description:
            "Two full chicken breasts, seasoned with salt, pepper and a squeeze of lemon. Nothing else needed. Served with steamed broccoli and wilted spinach. Pure, clean protein.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast (x2)", quantity: 300, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 150, unit: "g", category: "vegetable" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan", "air-fryer"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 562, protein: 97, carbs: 11, fat: 15, fiber: 5, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to medium-high with olive oil",
            "Season chicken breasts with salt and pepper",
            "Cook 5-6 min per side until golden and cooked through",
            "Steam broccoli 4 min (microwave or stovetop)",
            "Wilt spinach in pan with residual heat 1 min",
            "Squeeze lemon over chicken before serving",
          ],
        },
        {
          slug: "beef-fillet-lamb-chops-green-beans-sweet-potato",
          name: "Beef Fillet with Lamb Chops, Green Beans and Sweet Potato",
          description:
            "Pan-seared beef fillet alongside grilled lamb chops. Double protein plate. Served with crisp green beans and a small sweet potato. Simple seasoning only.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "lamb-chops", name: "Lamb chops (x2)", quantity: 140, unit: "g", category: "protein" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, sliced", quantity: 100, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 735, protein: 80, carbs: 24, fat: 36, fiber: 7, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook sweet potato slices in air fryer/oven at 200C 15 min, or pan-fry",
            "Heat pan to high with oil, season fillet and lamb chops with salt and pepper",
            "Sear fillet 3-4 min per side for medium",
            "Cook lamb chops 3 min per side",
            "Steam or pan-fry green beans 4 min",
            "Rest meat 3 min, plate with vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1297, protein: 177, carbs: 35, fat: 51, fiber: 12, sodium: 590 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "chicken-thigh-peri-peri-asparagus-brown-rice",
          name: "Chicken Thigh with Peri-Peri, Asparagus and Brown Rice",
          description:
            "Peri-peri marinated chicken thigh with grilled asparagus spears and a controlled portion of brown rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "oven", "pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 590, protein: 61, carbs: 28, fat: 27, fiber: 4, sodium: 375 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat chicken thigh in peri-peri marinade",
            "Air fry at 200C for 15-18 min or pan-fry 5-6 min per side",
            "Cook brown rice per packet instructions",
            "Grill asparagus in pan 3-4 min",
            "Plate rice, chicken and asparagus",
          ],
        },
        {
          slug: "beef-rump-mushrooms-baby-potatoes",
          name: "Beef Rump Steak with Mushrooms and Baby Potatoes",
          description:
            "Thick rump steak pan-seared with just salt and pepper, served with sauteed mushrooms and halved baby potatoes. Classic steakhouse simplicity.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "mushrooms", name: "Button mushrooms, halved", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 120, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 568, protein: 65, carbs: 24, fat: 24, fiber: 5, sodium: 250 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan high with oil, season rump with salt and pepper",
            "Sear rump 4 min per side for medium",
            "Rest steak, add mushrooms to same pan, cook 4 min until golden",
            "Plate potatoes, sliced steak, mushrooms on top",
          ],
        },
      ],
      dailyTotals: { calories: 1158, protein: 126, carbs: 52, fat: 51, fiber: 9, sodium: 625 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "lamb-leg-steak-green-beans-sweet-potato",
          name: "Lamb Leg Steak with Green Beans and Sweet Potato",
          description:
            "Pan-seared lamb leg steak with salt, pepper and a squeeze of lemon. Steamed green beans and roasted sweet potato on the side.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 130, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 100, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 510, protein: 59, carbs: 24, fat: 21, fiber: 6, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato wedges at 200C for 15 min",
            "Heat pan to high with oil, season lamb with salt and pepper",
            "Sear lamb leg steak 4 min per side",
            "Steam green beans 4 min",
            "Squeeze lemon over lamb, plate with vegetables",
          ],
        },
        {
          slug: "chicken-breast-chimichurri-broccoli-brown-rice",
          name: "Chicken Breast with Chimichurri, Broccoli and Brown Rice",
          description:
            "Grilled chicken breast drizzled with fresh chimichurri, paired with charred broccoli and brown rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 140, unit: "g", category: "vegetable" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 578, protein: 82, carbs: 27, fat: 17, fiber: 5, sodium: 335 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to medium-high, season chicken with salt and pepper",
            "Cook chicken breast 5-6 min per side until golden",
            "Char broccoli in same pan 3-4 min",
            "Drizzle chimichurri over sliced chicken, plate with rice and broccoli",
          ],
        },
      ],
      dailyTotals: { calories: 1088, protein: 141, carbs: 51, fat: 38, fiber: 11, sodium: 595 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "beef-sirloin-asparagus-baby-potatoes",
          name: "Beef Sirloin with Asparagus and Baby Potatoes",
          description:
            "Sirloin steak cooked in a hot pan, seasoned simply. Served with grilled asparagus and boiled baby potatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 120, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 582, protein: 63, carbs: 24, fat: 27, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season sirloin with salt and pepper",
            "Sear sirloin 3-4 min per side for medium",
            "Rest steak, grill asparagus in same pan 3-4 min",
            "Plate potatoes, sliced sirloin and asparagus",
          ],
        },
        {
          slug: "chicken-breast-teriyaki-spinach-white-rice",
          name: "Chicken Breast with Teriyaki Glaze, Spinach and White Rice",
          description:
            "Sliced chicken breast stir-fried in teriyaki glaze with baby spinach over white rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, sliced", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "white-rice", name: "White rice", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "teriyaki", name: "Teriyaki glaze pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 555, protein: 82, carbs: 30, fat: 13, fiber: 3, sodium: 575 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add sliced chicken",
            "Stir-fry chicken 4-5 min until cooked through",
            "Add teriyaki glaze and spinach, toss 1-2 min until wilted",
            "Serve over rice",
          ],
        },
      ],
      dailyTotals: { calories: 1137, protein: 145, carbs: 54, fat: 40, fiber: 8, sodium: 835 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "lamb-chops-roasted-vegetables",
          name: "Lamb Chops with Roasted Vegetables",
          description:
            "Three lamb chops, salt and pepper, pan-seared. Served with roasted zucchini, sweet peppers and a small portion of sweet potato.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "zucchini", name: "Zucchini, chunked", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 80, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 648, protein: 56, carbs: 20, fat: 39, fiber: 4, sodium: 250 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato and vegetables at 200C for 15 min",
            "Heat pan to high with oil, season lamb chops with salt and pepper",
            "Sear lamb chops 3 min per side",
            "Rest 2 min, plate with roasted vegetables",
          ],
        },
        {
          slug: "beef-fillet-garlic-herb-butter-broccoli",
          name: "Beef Fillet with Garlic Herb Butter and Broccoli",
          description:
            "Premium beef fillet topped with melting garlic herb butter. Served with a generous portion of steamed broccoli. No carb — pure protein and greens.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 200, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 680, protein: 60, carbs: 14, fat: 44, fiber: 5, sodium: 340 },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Heat pan to high with oil",
            "Season fillet with salt and pepper, sear 3-4 min per side for medium",
            "Rest steak 3 min, top with garlic herb butter",
            "Steam broccoli 4 min",
            "Plate fillet with melting butter and broccoli",
          ],
        },
      ],
      dailyTotals: { calories: 1328, protein: 116, carbs: 34, fat: 83, fiber: 9, sodium: 590 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "chicken-breast-lemon-herb-salad-sweet-potato",
          name: "Chicken Breast with Lemon Herb, Mixed Salad and Sweet Potato",
          description:
            "Grilled chicken breast with lemon herb dressing over a bed of mixed salad leaves with roasted sweet potato cubes. Light, fresh, high protein.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 70, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan", "air-fryer"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 575, protein: 81, carbs: 27, fat: 17, fiber: 5, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 15 min",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Slice chicken, arrange over mixed salad and tomatoes",
            "Add sweet potato cubes, drizzle lemon herb dressing",
          ],
        },
        {
          slug: "lamb-shoulder-slow-cook-spinach",
          name: "Lamb Shoulder Slow-Cook with Spinach",
          description:
            "Slow-cooked lamb shoulder, falling apart tender, seasoned with just salt, pepper, garlic and rosemary. Served on a bed of wilted spinach. Zero carb, maximum protein.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-shoulder", name: "Lamb shoulder, diced", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["slow-cooker", "oven"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 668, protein: 64, carbs: 4, fat: 44, fiber: 2, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan with oil, brown lamb pieces on all sides (5 min)",
            "Transfer to slow cooker or oven dish with garlic and rosemary",
            "Add 50ml water, cover",
            "Slow cooker: 4-6 hrs low. Oven: 160C covered for 2 hrs.",
            "Wilt spinach on a plate, pile lamb on top",
            "Season with salt and pepper",
          ],
        },
      ],
      dailyTotals: { calories: 1243, protein: 145, carbs: 31, fat: 61, fiber: 7, sodium: 660 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "korean-beef-strips-broccoli-brown-rice",
          name: "Korean Beef Strips with Broccoli and Brown Rice",
          description:
            "Thin beef strips stir-fried in Korean marinade with broccoli over brown rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump, thin strips", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 130, unit: "g", category: "vegetable" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "korean", name: "Korean marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 580, protein: 66, carbs: 32, fat: 22, fiber: 4, sodium: 580 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to high, add beef strips",
            "Stir-fry 3-4 min until browned",
            "Add Korean marinade and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "chicken-breast-beef-mince-green-beans",
          name: "Chicken Breast and Beef Mince Plate with Green Beans",
          description:
            "Grilled chicken breast alongside seasoned lean beef mince. Double protein plate. Served with steamed green beans. No sauce, no carb — pure fuel.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "beef-mince-lean", name: "Extra lean beef mince (5%)", quantity: 150, unit: "g", category: "protein" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 150, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 568, protein: 86, carbs: 9, fat: 22, fiber: 5, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Season chicken breast with salt and pepper, pan-fry 5-6 min per side",
            "In separate pan, cook beef mince with seasoning 5-6 min until browned",
            "Steam green beans 4 min",
            "Plate chicken, mince and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1148, protein: 152, carbs: 41, fat: 44, fiber: 9, sodium: 890 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1297, protein: 177, carbs: 35, fat: 51, fiber: 12, sodium: 590 } },
      { day: "Tuesday", nutrition: { calories: 1158, protein: 126, carbs: 52, fat: 51, fiber: 9, sodium: 625 } },
      { day: "Wednesday", nutrition: { calories: 1088, protein: 141, carbs: 51, fat: 38, fiber: 11, sodium: 595 } },
      { day: "Thursday", nutrition: { calories: 1137, protein: 145, carbs: 54, fat: 40, fiber: 8, sodium: 835 } },
      { day: "Friday", nutrition: { calories: 1328, protein: 116, carbs: 34, fat: 83, fiber: 9, sodium: 590 } },
      { day: "Saturday", nutrition: { calories: 1243, protein: 145, carbs: 31, fat: 61, fiber: 7, sodium: 660 } },
      { day: "Sunday", nutrition: { calories: 1148, protein: 152, carbs: 41, fat: 44, fiber: 9, sodium: 890 } },
    ],
    average: { calories: 1200, protein: 143, carbs: 43, fat: 53, fiber: 9, sodium: 684 },
  },
};
