import type { Plan } from "@/types";

export const steakNightPlan: Plan = {
  slug: "steak-night",
  name: "Steak Night",
  tagline: "Premium beef cuts. Every night.",
  goal: "premium-beef",
  description:
    "Premium plan with ribeye, sirloin, fillet, T-bone, rump rotation. Many meals are sauceless to let the beef shine. Side sauces (pepper, mushroom) are the natural add-ons.",
  difficulty: "intermediate",
  targetCalories: 2600,
  macroSplit: { protein: 35, carbs: 35, fat: 30 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2],
  proteinTypes: ["beef"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "beef-sirloin-baby-potatoes-asparagus",
          name: "Beef Sirloin with Baby Potatoes and Asparagus",
          description:
            "Thick-cut sirloin, seasoned with salt, pepper and a touch of olive oil. Pan-seared to your liking. Served with boiled baby potatoes and grilled asparagus.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 120, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 618, protein: 63, carbs: 35, fat: 28, fiber: 6, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil",
            "Season sirloin generously with salt and pepper",
            "Sear 3-4 min per side for medium (adjust to preference)",
            "Rest steak 3-4 min on a board",
            "Grill asparagus in same pan 3-4 min with residual fat",
            "Slice steak against the grain, plate with potatoes and asparagus",
          ],
        },
        {
          slug: "beef-ribeye-garlic-herb-butter-sweet-potato-mushrooms",
          name: "Beef Ribeye with Garlic Herb Butter, Sweet Potato Mash and Mushrooms",
          description:
            "Thick ribeye steak topped with melting garlic herb butter. Creamy sweet potato mash and golden sauteed mushrooms.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-ribeye", name: "Beef ribeye steak", quantity: 250, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, for mash", quantity: 200, unit: "g", category: "carb" },
            { ingredientId: "mushrooms", name: "Button mushrooms, halved", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 980, protein: 64, carbs: 44, fat: 60, fiber: 7, sodium: 410 },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato until soft, mash with salt and pepper",
            "Heat pan to high with oil, season ribeye generously",
            "Sear 4-5 min per side for medium",
            "Rest 4 min, top with garlic herb butter",
            "Saute mushrooms in same pan 4 min until golden",
            "Plate mash, ribeye with melting butter and mushrooms",
          ],
        },
      ],
      dailyTotals: { calories: 1598, protein: 127, carbs: 79, fat: 88, fiber: 13, sodium: 670 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "beef-rump-chimichurri-brown-rice-peppers",
          name: "Beef Rump with Chimichurri, Brown Rice and Roasted Peppers",
          description: "Pan-seared rump steak drizzled with chimichurri, served with brown rice and roasted sweet peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 632, protein: 65, carbs: 38, fat: 26, fiber: 4, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to high, season rump with salt and pepper",
            "Sear 4 min per side for medium, rest 3 min",
            "Roast peppers in same pan 3-4 min",
            "Slice steak, plate with rice and peppers, drizzle chimichurri",
          ],
        },
        {
          slug: "beef-fillet-broccoli-baby-potatoes-steak",
          name: "Beef Fillet with Broccoli and Baby Potatoes",
          description:
            "Premium fillet steak, simply seasoned and pan-seared. Steamed broccoli and halved baby potatoes. The fillet speaks for itself.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 150, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 160, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 572, protein: 56, carbs: 33, fat: 26, fiber: 7, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season fillet",
            "Sear 3-4 min per side for medium",
            "Rest 3 min, steam broccoli 4 min",
            "Plate potatoes, sliced fillet and broccoli",
          ],
        },
      ],
      dailyTotals: { calories: 1204, protein: 121, carbs: 71, fat: 52, fiber: 11, sodium: 560 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "t-bone-sweet-potato-wedges-green-beans",
          name: "T-Bone Steak with Sweet Potato Wedges and Green Beans",
          description:
            "Massive T-bone steak, salt and pepper, cooked in a screaming hot pan. Sweet potato wedges and steamed green beans.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-t-bone", name: "Beef T-bone steak", quantity: 280, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 868, protein: 70, carbs: 36, fat: 50, fiber: 7, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Air fry or oven-roast sweet potato wedges at 200C, 15 min",
            "Heat pan to very high with oil",
            "Season T-bone generously",
            "Sear 4-5 min per side for medium (bone side needs extra time)",
            "Rest 5 min — this is a thick cut",
            "Steam green beans 4 min",
            "Plate whole — T-bone is a showpiece cut",
          ],
        },
        {
          slug: "beef-sirloin-med-herbs-couscous-zucchini",
          name: "Beef Sirloin with Mediterranean Herbs, Couscous and Roasted Zucchini",
          description: "Sirloin steak marinated in Mediterranean herbs with fluffy couscous and roasted zucchini.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 588, protein: 60, carbs: 30, fat: 26, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Marinate sirloin in Mediterranean herbs",
            "Pan-sear 3-4 min per side for medium, rest 3 min",
            "Prepare couscous with boiling water",
            "Roast zucchini in same pan 3-4 min",
            "Fluff couscous, plate with sliced sirloin and zucchini",
          ],
        },
      ],
      dailyTotals: { calories: 1456, protein: 130, carbs: 66, fat: 76, fiber: 10, sodium: 590 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "beef-rump-korean-white-rice-broccoli",
          name: "Beef Rump with Korean Marinade, White Rice and Broccoli",
          description: "Thin beef rump strips stir-fried in Korean marinade with broccoli over white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump, thin strips", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "korean", name: "Korean marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "intermediate",
          nutrition: { calories: 618, protein: 66, carbs: 48, fat: 20, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add beef strips",
            "Stir-fry 3-4 min until browned",
            "Add Korean marinade and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "beef-ribeye-roasted-veg-mashed-potato",
          name: "Beef Ribeye with Roasted Vegetables and Mashed Potato",
          description:
            "Ribeye steak, salt and pepper only. Roasted sweet peppers, mushrooms and zucchini with creamy mashed white potato.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-ribeye", name: "Beef ribeye steak", quantity: 230, unit: "g", category: "protein" },
            { ingredientId: "white-potato", name: "White potato, for mash", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "mushrooms", name: "Button mushrooms, halved", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "zucchini", name: "Zucchini, chunked", quantity: 60, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan", "oven"],
          cookTime: 25,
          difficulty: "intermediate",
          nutrition: { calories: 858, protein: 58, carbs: 38, fat: 52, fiber: 5, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil potato until soft, mash with salt and pepper",
            "Roast peppers, mushrooms and zucchini at 200C for 15 min",
            "Heat pan to high, season ribeye generously",
            "Sear 4-5 min per side for medium, rest 4 min",
            "Plate mash, sliced ribeye and roasted vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1476, protein: 124, carbs: 86, fat: 72, fiber: 9, sodium: 780 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "beef-fillet-chimichurri-mixed-salad",
          name: "Beef Fillet with Chimichurri and Mixed Salad",
          description:
            "Pan-seared fillet steak sliced over mixed salad with cherry tomatoes and chimichurri. Light lunch, premium cut.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 70, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 80, unit: "g", category: "carb" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "intermediate",
          nutrition: { calories: 578, protein: 55, carbs: 22, fat: 32, fiber: 5, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 12 min",
            "Heat pan to high, season fillet",
            "Sear 3-4 min per side, rest 3 min",
            "Arrange salad and tomatoes on plate",
            "Slice fillet over salad, add sweet potato, drizzle chimichurri",
          ],
        },
        {
          slug: "beef-sirloin-garlic-herb-butter-asparagus-pasta",
          name: "Beef Sirloin with Garlic Herb Butter, Asparagus and Pasta",
          description: "Sirloin steak topped with garlic herb butter, grilled asparagus and penne pasta.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 752, protein: 64, carbs: 32, fat: 42, fiber: 3, sodium: 350 },
          allergens: ["dairy", "gluten"],
          dietary: { gf: "no", df: "no", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Heat pan to high, season sirloin",
            "Sear 3-4 min per side, rest 3 min",
            "Top with garlic herb butter",
            "Grill asparagus in same pan 3-4 min",
            "Plate pasta, sliced sirloin with butter and asparagus",
          ],
        },
      ],
      dailyTotals: { calories: 1330, protein: 119, carbs: 54, fat: 74, fiber: 8, sodium: 650 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "t-bone-smoky-bbq-corn-baby-potatoes",
          name: "T-Bone with Smoky BBQ, Corn and Baby Potatoes",
          description: "T-bone steak glazed in smoky BBQ with charred corn and roasted baby potatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-t-bone", name: "Beef T-bone steak", quantity: 260, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["pan", "bbq"],
          cookTime: 22,
          difficulty: "intermediate",
          nutrition: { calories: 852, protein: 66, carbs: 48, fat: 44, fiber: 5, sodium: 400 },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min, halve",
            "Glaze T-bone in smoky BBQ",
            "Pan-sear or BBQ 4-5 min per side for medium",
            "Rest 5 min, char corn in a dry pan 4 min",
            "Plate T-bone with potatoes and charred corn",
          ],
        },
        {
          slug: "beef-rump-spinach-sweet-potato-steak",
          name: "Beef Rump with Spinach and Sweet Potato",
          description:
            "Thick rump steak, simply seasoned, pan-seared. Wilted spinach and roasted sweet potato. Clean Saturday dinner.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 130, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 560, protein: 64, carbs: 28, fat: 22, fiber: 5, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 15 min",
            "Heat pan to high, season rump with salt and pepper",
            "Sear 4 min per side for medium, rest 3 min",
            "Wilt spinach in same pan 1 min",
            "Plate sweet potato, sliced rump and spinach",
          ],
        },
      ],
      dailyTotals: { calories: 1412, protein: 130, carbs: 76, fat: 66, fiber: 10, sodium: 680 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "beef-ribeye-teriyaki-brown-rice-broccoli",
          name: "Beef Ribeye with Teriyaki Glaze, Brown Rice and Broccoli",
          description:
            "Something different — ribeye sliced thin and glazed in teriyaki, served over brown rice with charred broccoli. Asian-inspired steak night.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-ribeye", name: "Beef ribeye, sliced thin", quantity: 230, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "teriyaki", name: "Teriyaki glaze pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 822, protein: 60, carbs: 46, fat: 48, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to high, sear thin ribeye slices 2 min per side",
            "Add teriyaki glaze, toss to coat",
            "Char broccoli in same pan 3-4 min",
            "Serve glazed ribeye over rice with broccoli",
          ],
        },
        {
          slug: "beef-fillet-green-beans-mashed-potato-sunday",
          name: "Beef Fillet with Green Beans and Mashed Potato",
          description:
            "Sunday's fillet. Simply seasoned, perfectly seared. Steamed green beans and smooth mashed potato. No sauce needed on a cut this good.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-potato", name: "White potato, for mash", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 130, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 612, protein: 61, carbs: 36, fat: 28, fiber: 7, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil potato until soft, mash with salt and pepper",
            "Heat pan to high, season fillet generously",
            "Sear 3-4 min per side for medium, rest 3 min",
            "Steam green beans 4 min",
            "Plate mash, sliced fillet and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1434, protein: 121, carbs: 82, fat: 76, fiber: 11, sodium: 760 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1598, protein: 127, carbs: 79, fat: 88, fiber: 13, sodium: 670 } },
      { day: "Tuesday", nutrition: { calories: 1204, protein: 121, carbs: 71, fat: 52, fiber: 11, sodium: 560 } },
      { day: "Wednesday", nutrition: { calories: 1456, protein: 130, carbs: 66, fat: 76, fiber: 10, sodium: 590 } },
      { day: "Thursday", nutrition: { calories: 1476, protein: 124, carbs: 86, fat: 72, fiber: 9, sodium: 780 } },
      { day: "Friday", nutrition: { calories: 1330, protein: 119, carbs: 54, fat: 74, fiber: 8, sodium: 650 } },
      { day: "Saturday", nutrition: { calories: 1412, protein: 130, carbs: 76, fat: 66, fiber: 10, sodium: 680 } },
      { day: "Sunday", nutrition: { calories: 1434, protein: 121, carbs: 82, fat: 76, fiber: 11, sodium: 760 } },
    ],
    average: { calories: 1416, protein: 125, carbs: 73, fat: 72, fiber: 10, sodium: 670 },
  },
};
