import type { Plan } from "@/types";

export const theBreakfastClubPlan: Plan = {
  slug: "the-breakfast-club",
  name: "The Breakfast Club",
  tagline: "Every meal sorted. Breakfast to dinner.",
  goal: "full-day",
  description:
    "Full 3-meal coverage every day. Breakfasts rotate between protein pancakes, oats, eggs, and turkey mince egg cups. Lunch and dinner are balanced with all three proteins. Mix of sauced and sauceless.",
  difficulty: "beginner",
  targetCalories: 2400,
  macroSplit: { protein: 35, carbs: 40, fat: 25 },
  mealsPerDay: 3,
  includesBreakfast: true,
  durationOptions: [5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "bc-protein-pancakes-banana-honey-monday",
          name: "Protein Pancakes with Banana and Honey",
          description: "Fluffy protein pancakes topped with sliced banana and a drizzle of raw honey.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 453, protein: 41, carbs: 60, fat: 8, fiber: 4, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Top with sliced banana and drizzle honey",
          ],
        },
        {
          slug: "bc-chicken-breast-peri-peri-white-rice-broccoli",
          name: "Chicken Breast with Peri-Peri, White Rice and Broccoli",
          description: "Peri-peri marinated chicken breast with fluffy white rice and steamed broccoli.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 572, protein: 68, carbs: 46, fat: 12, fiber: 4, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Coat chicken breast in peri-peri marinade",
            "Air fry at 200C for 15 min or pan-fry 5-6 min per side",
            "Steam broccoli 4 min",
            "Plate rice, chicken and broccoli",
          ],
        },
        {
          slug: "bc-beef-rump-baby-potatoes-green-beans",
          name: "Beef Rump with Baby Potatoes and Green Beans",
          description: "Pan-seared rump steak with baby potatoes and steamed green beans. Simple, satisfying dinner.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 488, protein: 54, carbs: 28, fat: 19, fiber: 6, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season rump with salt and pepper",
            "Sear 4 min per side for medium, rest 3 min",
            "Steam green beans 4 min",
            "Plate potatoes, sliced rump and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1513, protein: 163, carbs: 134, fat: 39, fiber: 14, sodium: 840 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "bc-oats-eggs-tuesday",
          name: "Rolled Oats with Eggs",
          description: "Warm rolled oats paired with two scrambled free-range eggs. Protein and carbs to start the day.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x2)", quantity: 120, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 490, protein: 25, carbs: 56, fat: 18, fiber: 8, sodium: 200 },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook oats with water 3-5 min",
            "Scramble eggs in a separate pan 2-3 min",
            "Serve oats in bowl with eggs on the side",
          ],
        },
        {
          slug: "bc-lamb-leg-steak-chimichurri-brown-rice-peppers",
          name: "Lamb Leg Steak with Chimichurri, Brown Rice and Roasted Peppers",
          description: "Pan-seared lamb leg steak drizzled with chimichurri, brown rice and roasted sweet peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 578, protein: 56, carbs: 38, fat: 22, fiber: 4, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to high, season lamb with salt and pepper",
            "Sear 4 min per side, rest 3 min",
            "Roast peppers in same pan 3-4 min",
            "Slice lamb, plate with rice and peppers, drizzle chimichurri",
          ],
        },
        {
          slug: "bc-chicken-thigh-coconut-curry-white-rice-spinach",
          name: "Chicken Thigh Coconut Curry with White Rice and Spinach",
          description: "Diced chicken thigh in coconut curry sauce with spinach over white rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, diced", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 638, protein: 52, carbs: 50, fat: 28, fiber: 3, sodium: 360 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan, cook diced chicken thigh 4-5 min",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over white rice",
          ],
        },
      ],
      dailyTotals: { calories: 1706, protein: 133, carbs: 144, fat: 68, fiber: 15, sodium: 860 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "bc-turkey-mince-egg-cups-toast",
          name: "Turkey Mince Egg Cups with Toast",
          description:
            "Savoury breakfast — turkey mince baked with eggs in a muffin tray. Served with toasted sourdough. High protein start.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "turkey-mince", name: "Turkey mince", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x2)", quantity: 120, unit: "g", category: "breakfast" },
            { ingredientId: "sourdough", name: "Sourdough bread", quantity: 70, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 20, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["oven"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 425, protein: 35, carbs: 30, fat: 18, fiber: 2, sodium: 400 },
          allergens: ["eggs", "gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Preheat oven to 180C",
            "Press turkey mince into muffin tray holes to form cups",
            "Add a few spinach leaves into each cup",
            "Crack an egg into each cup",
            "Season, bake 12-15 min until egg is set",
            "Toast sourdough, serve alongside",
          ],
        },
        {
          slug: "bc-chicken-breast-teriyaki-broccoli-white-rice",
          name: "Chicken Breast with Teriyaki, Broccoli and White Rice",
          description: "Chicken breast stir-fried in teriyaki glaze with broccoli over white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, sliced", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "teriyaki", name: "Teriyaki glaze pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 568, protein: 68, carbs: 50, fat: 10, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add sliced chicken",
            "Stir-fry 4-5 min until cooked through",
            "Add teriyaki glaze and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "bc-beef-sirloin-med-herbs-couscous-roasted-veg",
          name: "Beef Sirloin with Mediterranean Herbs, Roasted Vegetables and Couscous",
          description: "Mediterranean herb sirloin with fluffy couscous and roasted zucchini and peppers.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 558, protein: 55, carbs: 34, fat: 24, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Marinate sirloin in Mediterranean herbs",
            "Pan-sear 3-4 min per side, rest 3 min",
            "Prepare couscous with boiling water",
            "Roast zucchini and peppers in same pan 3-4 min",
            "Fluff couscous, plate with sliced sirloin and roasted vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1551, protein: 158, carbs: 114, fat: 52, fiber: 9, sodium: 1210 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "bc-protein-pancakes-oats-thursday",
          name: "Protein Pancakes with Oats",
          description: "Protein pancakes mixed with oats and drizzled with honey. Hearty Thursday breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 160, unit: "g", category: "breakfast" },
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 60, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: { calories: 542, protein: 40, carbs: 74, fat: 10, fiber: 9, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Mix oats into pancake batter",
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Drizzle with honey",
          ],
        },
        {
          slug: "bc-lamb-chops-baby-potatoes-asparagus",
          name: "Lamb Chops with Baby Potatoes and Asparagus",
          description: "Pan-seared lamb chops with baby potatoes and grilled asparagus.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x2)", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 490, protein: 43, carbs: 28, fat: 26, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season lamb chops",
            "Sear 3 min per side, rest 2 min",
            "Grill asparagus in same pan 3-4 min",
            "Plate potatoes, lamb chops and asparagus",
          ],
        },
        {
          slug: "bc-chicken-thigh-smoky-bbq-sweet-potato-corn",
          name: "Chicken Thigh with Smoky BBQ, Sweet Potato and Corn",
          description: "Smoky BBQ chicken thighs with sweet potato wedges and charred corn.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 588, protein: 54, carbs: 50, fat: 22, fiber: 6, sodium: 420 },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat chicken thighs in smoky BBQ marinade",
            "Arrange sweet potato wedges on tray",
            "Air fry or oven bake at 200C for 18-20 min",
            "Char corn in a dry pan 3-4 min",
            "Plate chicken, sweet potato and corn",
          ],
        },
      ],
      dailyTotals: { calories: 1620, protein: 137, carbs: 152, fat: 58, fiber: 20, sodium: 880 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "bc-eggs-spinach-toast-friday",
          name: "Eggs with Spinach and Toast",
          description: "Scrambled eggs with spinach and toasted sourdough. Quick Friday breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x3)", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "sourdough", name: "Sourdough bread", quantity: 70, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 6,
          difficulty: "beginner",
          nutrition: { calories: 388, protein: 25, carbs: 30, fat: 20, fiber: 3, sodium: 400 },
          allergens: ["eggs", "gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Toast sourdough",
            "Heat pan with a touch of oil, wilt spinach 1 min",
            "Add beaten eggs, scramble 2-3 min",
            "Serve eggs and spinach with toast",
          ],
        },
        {
          slug: "bc-beef-mince-tomato-curry-brown-rice",
          name: "Beef Mince Tomato Curry with Brown Rice",
          description: "Beef mince in tomato herb curry sauce with spinach over brown rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-mince-regular", name: "Beef mince (15%)", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 608, protein: 40, carbs: 50, fat: 30, fiber: 4, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Brown beef mince in hot pan 5-6 min",
            "Add tomato curry sauce, simmer 8-10 min",
            "Stir in spinach until wilted",
            "Serve over brown rice",
          ],
        },
        {
          slug: "bc-chicken-breast-garlic-herb-butter-mash-green-beans",
          name: "Chicken Breast with Garlic Herb Butter, Mashed Potato and Green Beans",
          description: "Grilled chicken breast topped with garlic herb butter, creamy mashed potato and steamed green beans.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-potato", name: "White potato, for mash", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 590, protein: 67, carbs: 36, fat: 20, fiber: 6, sodium: 350 },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Boil potato until soft, mash with salt and pepper",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Top with garlic herb butter",
            "Steam green beans 4 min",
            "Plate mash, chicken with melting butter and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1586, protein: 132, carbs: 116, fat: 70, fiber: 13, sodium: 1130 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "bc-turkey-mince-egg-cups-mushrooms-saturday",
          name: "Turkey Mince Egg Cups with Mushrooms",
          description: "Turkey mince baked with eggs and diced mushrooms. High protein, low carb Saturday breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "turkey-mince", name: "Turkey mince", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x2)", quantity: 120, unit: "g", category: "breakfast" },
            { ingredientId: "mushrooms", name: "Button mushrooms, diced", quantity: 40, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["oven"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 310, protein: 33, carbs: 2, fat: 18, fiber: 1, sodium: 350 },
          allergens: ["eggs"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Preheat oven to 180C",
            "Press turkey mince into muffin tray, add diced mushrooms",
            "Crack an egg into each cup",
            "Season, bake 12-15 min until egg is set",
          ],
        },
        {
          slug: "bc-korean-chicken-thigh-white-rice-broccoli",
          name: "Korean Chicken Thigh with White Rice and Broccoli",
          description: "Korean-marinated chicken thigh stir-fried with broccoli over white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, sliced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "korean", name: "Korean marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 690, protein: 60, carbs: 54, fat: 28, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add sliced chicken thigh",
            "Stir-fry 4-5 min until cooked through",
            "Add Korean marinade and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "bc-lamb-leg-steak-sweet-potato-spinach",
          name: "Lamb Leg Steak with Sweet Potato and Spinach",
          description: "Pan-seared lamb leg steak with roasted sweet potato and wilted spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 482, protein: 54, carbs: 30, fat: 18, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 15 min",
            "Heat pan to high, season lamb with salt and pepper",
            "Sear 4 min per side, rest 3 min",
            "Wilt spinach in same pan 1 min",
            "Squeeze lemon over lamb, plate with sweet potato and spinach",
          ],
        },
      ],
      dailyTotals: { calories: 1482, protein: 147, carbs: 86, fat: 64, fiber: 10, sodium: 1110 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "bc-protein-pancakes-banana-oats-sunday",
          name: "Protein Pancakes with Banana and Oats",
          description: "Sunday special — protein pancakes with oats, banana and honey. Hearty start.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 60, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: { calories: 538, protein: 42, carbs: 76, fat: 9, fiber: 7, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Mix oats into pancake batter",
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes, cook 2-3 min per side",
            "Top with sliced banana and drizzle honey",
          ],
        },
        {
          slug: "bc-chicken-breast-lemon-herb-salad-baby-potatoes",
          name: "Chicken Breast with Lemon Herb, Mixed Salad and Baby Potatoes",
          description: "Grilled chicken breast with lemon herb dressing, mixed salad and baby potatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 510, protein: 65, carbs: 28, fat: 17, fiber: 4, sodium: 340 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Arrange salad and tomatoes on plate",
            "Slice chicken over salad, add potatoes",
            "Drizzle lemon herb dressing",
          ],
        },
        {
          slug: "bc-beef-sirloin-chimichurri-sweet-potato-asparagus",
          name: "Beef Sirloin with Chimichurri, Sweet Potato and Asparagus",
          description: "Pan-seared sirloin drizzled with chimichurri, roasted sweet potato wedges and grilled asparagus.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 548, protein: 53, carbs: 28, fat: 26, fiber: 5, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato wedges at 200C for 15 min",
            "Heat pan to high, season sirloin",
            "Sear 3-4 min per side for medium, rest 3 min",
            "Grill asparagus in same pan 3-4 min",
            "Slice steak, plate with sweet potato and asparagus, drizzle chimichurri",
          ],
        },
      ],
      dailyTotals: { calories: 1596, protein: 160, carbs: 132, fat: 52, fiber: 16, sodium: 840 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1513, protein: 163, carbs: 134, fat: 39, fiber: 14, sodium: 840 } },
      { day: "Tuesday", nutrition: { calories: 1706, protein: 133, carbs: 144, fat: 68, fiber: 15, sodium: 860 } },
      { day: "Wednesday", nutrition: { calories: 1551, protein: 158, carbs: 114, fat: 52, fiber: 9, sodium: 1210 } },
      { day: "Thursday", nutrition: { calories: 1620, protein: 137, carbs: 152, fat: 58, fiber: 20, sodium: 880 } },
      { day: "Friday", nutrition: { calories: 1586, protein: 132, carbs: 116, fat: 70, fiber: 13, sodium: 1130 } },
      { day: "Saturday", nutrition: { calories: 1482, protein: 147, carbs: 86, fat: 64, fiber: 10, sodium: 1110 } },
      { day: "Sunday", nutrition: { calories: 1596, protein: 160, carbs: 132, fat: 52, fiber: 16, sodium: 840 } },
    ],
    average: { calories: 1579, protein: 147, carbs: 125, fat: 58, fiber: 14, sodium: 981 },
  },
};
