import type { Plan } from "@/types";

export const theAthletePlan: Plan = {
  slug: "the-athlete",
  name: "The Athlete",
  tagline: "Training-optimized. Carb cycling built in.",
  goal: "athletic",
  description:
    "Carb cycling plan. Training days (Mon/Tue/Thu/Fri) are high carb with rice, pasta, sweet potato, oats, pancakes. Rest days (Wed/Sat/Sun) are low carb — protein and vegetables only. Protein stays consistently high. Includes breakfast.",
  difficulty: "advanced",
  targetCalories: 2500,
  macroSplit: { protein: 35, carbs: 35, fat: 30 },
  mealsPerDay: 3,
  includesBreakfast: true,
  durationOptions: [5, 7],
  servingOptions: [1, 2],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  featured: true,
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "athlete-protein-pancakes-oats-banana-monday",
          name: "Protein Pancakes with Oats and Banana",
          description: "Big training day breakfast — protein pancakes mixed with oats, topped with banana and honey.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 200, unit: "g", category: "breakfast" },
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 15, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: { calories: 738, protein: 52, carbs: 105, fat: 14, fiber: 13, sodium: 250 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Mix oats into pancake batter",
            "Heat pan to medium with a touch of oil",
            "Pour batter into 4-5 pancakes",
            "Cook 2-3 min per side until golden",
            "Top with sliced banana and drizzle honey",
          ],
        },
        {
          slug: "athlete-chicken-breast-teriyaki-white-rice-broccoli",
          name: "Chicken Breast with White Rice, Broccoli and Teriyaki Glaze",
          description: "Training day fuel — chicken breast stir-fried in teriyaki with broccoli over a generous portion of white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, sliced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 160, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "teriyaki", name: "Teriyaki glaze pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "teriyaki",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 638, protein: 74, carbs: 60, fat: 12, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add sliced chicken",
            "Stir-fry 4-5 min until cooked through",
            "Add teriyaki glaze and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "athlete-beef-sirloin-sweet-potato-green-beans-monday",
          name: "Beef Sirloin with Sweet Potato Mash and Green Beans",
          description: "Pan-seared sirloin with sweet potato mash and steamed green beans. Post-training recovery.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, for mash", quantity: 220, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 600, protein: 58, carbs: 50, fat: 22, fiber: 8, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato until soft, mash with salt and pepper",
            "Heat pan to high with oil, season sirloin",
            "Sear 3-4 min per side for medium, rest 3 min",
            "Steam green beans 4 min",
            "Plate mash, sliced sirloin and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1976, protein: 184, carbs: 215, fat: 48, fiber: 25, sodium: 1010 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "athlete-oats-eggs-toast-tuesday",
          name: "Rolled Oats with Eggs and Toast",
          description: "Oats, scrambled eggs and toasted sourdough. Solid training day breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x2)", quantity: 120, unit: "g", category: "breakfast" },
            { ingredientId: "sourdough", name: "Sourdough bread", quantity: 70, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 620, protein: 28, carbs: 80, fat: 19, fiber: 11, sodium: 350 },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook oats with water 3-5 min",
            "Scramble eggs in a separate pan 2-3 min",
            "Toast sourdough",
            "Serve oats in bowl with eggs and toast on the side",
          ],
        },
        {
          slug: "athlete-chicken-thigh-peri-peri-pasta-peppers",
          name: "Chicken Thigh with Peri-Peri, Pasta and Sweet Peppers",
          description: "Peri-peri chicken thighs with penne pasta and roasted sweet peppers. High carb training fuel.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 728, protein: 62, carbs: 56, fat: 30, fiber: 4, sodium: 400 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Coat chicken thighs in peri-peri marinade",
            "Air fry at 200C for 15 min or pan-fry 5-6 min per side",
            "Roast peppers in same pan 3-4 min",
            "Slice chicken, toss with pasta and peppers",
          ],
        },
        {
          slug: "athlete-beef-rump-chimichurri-white-rice-corn",
          name: "Beef Rump with Chimichurri, White Rice and Roasted Corn",
          description: "Pan-seared rump steak drizzled with chimichurri, white rice and charred corn.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 632, protein: 60, carbs: 54, fat: 22, fiber: 4, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, season rump with salt and pepper",
            "Sear 4 min per side for medium, rest 3 min",
            "Char corn in a dry pan 4 min",
            "Slice steak, plate with rice and corn, drizzle chimichurri",
          ],
        },
      ],
      dailyTotals: { calories: 1980, protein: 150, carbs: 190, fat: 71, fiber: 19, sodium: 1050 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "athlete-eggs-scrambled-spinach-rest",
          name: "Eggs Scrambled with Spinach",
          description: "Rest day breakfast — scrambled eggs with spinach. No carbs. Protein and healthy fats only.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x3)", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 5,
          difficulty: "beginner",
          nutrition: { calories: 280, protein: 20, carbs: 3, fat: 21, fiber: 1, sodium: 350 },
          allergens: ["eggs"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan with a touch of oil",
            "Add spinach, wilt 1 min",
            "Pour in beaten eggs, scramble gently 2-3 min",
            "Season with salt and pepper",
          ],
        },
        {
          slug: "athlete-chicken-breast-broccoli-asparagus-rest",
          name: "Chicken Breast with Broccoli and Asparagus",
          description: "Double portion of green veg with grilled chicken. Rest day plate — protein and greens only.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 150, unit: "g", category: "vegetable" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 448, protein: 73, carbs: 11, fat: 14, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Season chicken breast with salt and pepper",
            "Pan-fry 5-6 min per side until golden and cooked through",
            "Steam broccoli and asparagus 4 min",
            "Plate chicken with vegetables",
          ],
        },
        {
          slug: "athlete-lamb-chops-mushrooms-spinach-rest",
          name: "Lamb Chops with Mushrooms and Spinach",
          description: "Pan-seared lamb chops with sauteed mushrooms and wilted spinach. Rich in protein and fat for rest day recovery.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "mushrooms", name: "Button mushrooms, halved", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 608, protein: 57, carbs: 5, fat: 41, fiber: 3, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to high with oil, season lamb chops",
            "Sear 3 min per side, rest 2 min",
            "Add mushrooms to same pan, cook 4 min until golden",
            "Wilt spinach in pan 1 min",
            "Plate lamb chops with mushrooms and spinach",
          ],
        },
      ],
      dailyTotals: { calories: 1336, protein: 150, carbs: 19, fat: 76, fiber: 9, sodium: 890 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "athlete-protein-pancakes-banana-thursday",
          name: "Protein Pancakes with Banana",
          description: "Training day pancakes with sliced banana and honey. Quick fuel before the gym.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 453, protein: 41, carbs: 60, fat: 8, fiber: 4, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Top with sliced banana and drizzle honey",
          ],
        },
        {
          slug: "athlete-beef-mince-smoky-bbq-sweet-potato-corn",
          name: "Beef Mince with Smoky BBQ, Sweet Potato and Corn",
          description: "Beef mince cooked in smoky BBQ marinade with sweet potato mash and charred corn.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-mince-regular", name: "Beef mince (15%)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, for mash", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 702, protein: 42, carbs: 62, fat: 34, fiber: 8, sodium: 400 },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil sweet potato until soft, mash with salt and pepper",
            "Brown beef mince in hot pan 5-6 min",
            "Add smoky BBQ marinade, cook 3-4 min more",
            "Char corn in a dry pan 4 min",
            "Plate mash, BBQ mince and charred corn",
          ],
        },
        {
          slug: "athlete-chicken-thigh-korean-white-rice-broccoli",
          name: "Chicken Thigh with Korean Marinade, White Rice and Broccoli",
          description: "Korean-marinated chicken thigh stir-fried with broccoli over a generous portion of white rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, sliced (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "korean", name: "Korean marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 722, protein: 60, carbs: 62, fat: 28, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, add sliced chicken thigh",
            "Stir-fry 4-5 min until cooked through",
            "Add Korean marinade and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
      ],
      dailyTotals: { calories: 1877, protein: 143, carbs: 184, fat: 70, fiber: 16, sodium: 1100 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "athlete-oats-banana-honey-friday",
          name: "Rolled Oats with Banana and Honey",
          description: "Big bowl of oats with banana and honey. Simple training day carb load.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 100, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 15, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 5,
          difficulty: "beginner",
          nutrition: { calories: 498, protein: 13, carbs: 92, fat: 7, fiber: 11, sodium: 10 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook oats with water 3-5 min",
            "Top with sliced banana and drizzle honey",
          ],
        },
        {
          slug: "athlete-lamb-leg-steak-med-herbs-brown-rice-peppers",
          name: "Lamb Leg Steak with Mediterranean Herbs, Brown Rice and Peppers",
          description: "Mediterranean herb lamb leg steak with brown rice and roasted sweet peppers.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 620, protein: 62, carbs: 44, fat: 22, fiber: 4, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Rub lamb leg steak with Mediterranean herb marinade",
            "Pan-sear 4 min per side, rest 3 min",
            "Roast peppers in same pan 3-4 min",
            "Plate rice, sliced lamb and peppers",
          ],
        },
        {
          slug: "athlete-chicken-breast-coconut-curry-white-rice-spinach",
          name: "Chicken Breast with Coconut Curry, White Rice and Spinach",
          description: "Diced chicken breast in coconut curry sauce with spinach over white rice. Training day recovery.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, diced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 648, protein: 74, carbs: 56, fat: 16, fiber: 4, sodium: 360 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan, cook diced chicken 4-5 min",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over white rice",
          ],
        },
      ],
      dailyTotals: { calories: 1766, protein: 149, carbs: 192, fat: 45, fiber: 19, sodium: 680 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "athlete-eggs-spinach-mushrooms-rest-saturday",
          name: "Eggs with Spinach and Mushrooms",
          description: "Rest day breakfast — eggs with spinach and mushrooms. No carbs.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x3)", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "mushrooms", name: "Button mushrooms, sliced", quantity: 60, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 295, protein: 22, carbs: 4, fat: 22, fiber: 2, sodium: 350 },
          allergens: ["eggs"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan with oil, saute mushrooms 3 min",
            "Add spinach, wilt 1 min",
            "Pour in beaten eggs, scramble 2-3 min",
            "Season with salt and pepper",
          ],
        },
        {
          slug: "athlete-beef-fillet-green-beans-asparagus-rest",
          name: "Beef Fillet with Green Beans and Asparagus",
          description: "Premium fillet steak with green beans and asparagus. No carb rest day plate.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-fillet", name: "Beef fillet steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 528, protein: 56, carbs: 11, fat: 30, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to high with oil, season fillet",
            "Sear 3-4 min per side for medium, rest 3 min",
            "Steam green beans and asparagus 4 min",
            "Plate fillet with vegetables",
          ],
        },
        {
          slug: "athlete-chicken-thigh-peri-peri-broccoli-spinach-rest",
          name: "Chicken Thigh with Peri-Peri, Broccoli and Spinach",
          description: "Peri-peri chicken thighs with broccoli and wilted spinach. No carb rest day dinner.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "oven", "pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 538, protein: 56, carbs: 9, fat: 32, fiber: 4, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat chicken thighs in peri-peri marinade",
            "Air fry at 200C for 15 min or pan-fry 5-6 min per side",
            "Steam broccoli 4 min",
            "Wilt spinach in pan 1 min",
            "Plate chicken with broccoli and spinach",
          ],
        },
      ],
      dailyTotals: { calories: 1361, protein: 134, carbs: 24, fat: 84, fiber: 11, sodium: 990 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "athlete-eggs-mushrooms-rest-sunday",
          name: "Eggs with Mushrooms",
          description: "Rest day breakfast — eggs and mushrooms. No carbs.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x3)", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "mushrooms", name: "Button mushrooms, sliced", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 6,
          difficulty: "beginner",
          nutrition: { calories: 288, protein: 21, carbs: 4, fat: 22, fiber: 1, sodium: 350 },
          allergens: ["eggs"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan with oil, saute mushrooms 3 min",
            "Pour in beaten eggs, scramble 2-3 min",
            "Season with salt and pepper",
          ],
        },
        {
          slug: "athlete-lamb-chops-chimichurri-broccoli-spinach-rest",
          name: "Lamb Chops with Chimichurri, Broccoli and Spinach",
          description: "Pan-seared lamb chops drizzled with chimichurri, with broccoli and spinach. No carb rest day.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 628, protein: 58, carbs: 9, fat: 42, fiber: 4, sodium: 280 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to high with oil, season lamb chops",
            "Sear 3 min per side, rest 2 min",
            "Steam broccoli 4 min, wilt spinach in pan 1 min",
            "Plate lamb chops with vegetables, drizzle chimichurri",
          ],
        },
        {
          slug: "athlete-beef-rump-green-beans-mushrooms-rest",
          name: "Beef Rump with Green Beans and Mushrooms",
          description: "Rump steak, salt and pepper, pan-seared. Steamed green beans and sauteed mushrooms. Rest day recovery meal.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "mushrooms", name: "Button mushrooms, halved", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 498, protein: 60, carbs: 11, fat: 24, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Heat pan to high with oil, season rump with salt and pepper",
            "Sear 4 min per side for medium, rest 3 min",
            "Saute mushrooms in same pan 4 min",
            "Steam green beans 4 min",
            "Plate sliced rump with mushrooms and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1414, protein: 139, carbs: 24, fat: 88, fiber: 10, sodium: 890 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1976, protein: 184, carbs: 215, fat: 48, fiber: 25, sodium: 1010 } },
      { day: "Tuesday", nutrition: { calories: 1980, protein: 150, carbs: 190, fat: 71, fiber: 19, sodium: 1050 } },
      { day: "Wednesday", nutrition: { calories: 1336, protein: 150, carbs: 19, fat: 76, fiber: 9, sodium: 890 } },
      { day: "Thursday", nutrition: { calories: 1877, protein: 143, carbs: 184, fat: 70, fiber: 16, sodium: 1100 } },
      { day: "Friday", nutrition: { calories: 1766, protein: 149, carbs: 192, fat: 45, fiber: 19, sodium: 680 } },
      { day: "Saturday", nutrition: { calories: 1361, protein: 134, carbs: 24, fat: 84, fiber: 11, sodium: 990 } },
      { day: "Sunday", nutrition: { calories: 1414, protein: 139, carbs: 24, fat: 88, fiber: 10, sodium: 890 } },
    ],
    average: { calories: 1673, protein: 150, carbs: 121, fat: 69, fiber: 16, sodium: 944 },
  },
};
