import type { Plan } from "@/types";

export const theMediterraneanPlan: Plan = {
  slug: "the-mediterranean",
  name: "The Mediterranean",
  tagline: "Lamb-forward. Sun-drenched flavours.",
  goal: "mediterranean",
  description:
    "Warm spices, olive oil, couscous, roasted veg. Lamb is the hero protein with chicken as support. Good balance of sauced (Mediterranean herb, shawarma) and simple olive oil + lemon plates.",
  difficulty: "intermediate",
  targetCalories: 2300,
  macroSplit: { protein: 30, carbs: 40, fat: 30 },
  mealsPerDay: 2,
  includesBreakfast: false,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["lamb", "chicken"],
  dietaryOptions: ["gf", "df", "lf"],
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "lamb-cutlets-med-herbs-roasted-veg-couscous",
          name: "Lamb Cutlets with Mediterranean Herbs, Roasted Vegetables and Couscous",
          description: "Pan-seared lamb cutlets rubbed in Mediterranean herbs with fluffy couscous and roasted zucchini, peppers and cherry tomatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-cutlets", name: "Lamb cutlets (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 752, protein: 58, carbs: 38, fat: 42, fiber: 4, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub lamb cutlets with Mediterranean herb marinade",
            "Heat pan to high, sear cutlets 3 min per side",
            "Prepare couscous with boiling water",
            "Roast zucchini, peppers and tomatoes 10 min at 200C",
            "Fluff couscous, plate with cutlets and roasted vegetables",
          ],
        },
        {
          slug: "chicken-thigh-lemon-herb-baby-potatoes-spinach-med",
          name: "Chicken Thigh with Lemon Herb, Baby Potatoes and Spinach",
          description: "Pan-fried chicken thighs with lemon herb dressing, baby potatoes and wilted spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 160, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 628, protein: 58, carbs: 32, fat: 30, fiber: 5, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Pan-fry chicken thighs 5-6 min per side",
            "Wilt spinach in same pan 1 min",
            "Plate potatoes, chicken and spinach, drizzle lemon herb dressing",
          ],
        },
      ],
      dailyTotals: { calories: 1380, protein: 116, carbs: 70, fat: 72, fiber: 9, sodium: 620 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "lamb-leg-steak-roasted-veg-brown-rice-med",
          name: "Lamb Leg Steak with Roasted Vegetables and Brown Rice",
          description:
            "Pan-seared lamb leg steak with salt, pepper, olive oil and a squeeze of lemon. Served with roasted sweet peppers, zucchini and brown rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 580, protein: 60, carbs: 34, fat: 24, fiber: 4, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan to high with olive oil, season lamb with salt and pepper",
            "Sear lamb leg steak 4 min per side",
            "Roast peppers and zucchini in same pan 4 min",
            "Squeeze lemon over lamb, plate with rice and roasted vegetables",
          ],
        },
        {
          slug: "chicken-breast-shawarma-white-rice-salad-med",
          name: "Chicken Breast with Shawarma Spice, White Rice and Mixed Salad",
          description: "Shawarma-spiced chicken breast with white rice and a fresh mixed salad.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "air-fryer"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 582, protein: 68, carbs: 46, fat: 14, fiber: 3, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Rub chicken breast with shawarma spice and olive oil",
            "Pan-fry 5-6 min per side until cooked through",
            "Arrange salad and tomatoes on plate",
            "Slice chicken, plate with rice and salad",
          ],
        },
      ],
      dailyTotals: { calories: 1162, protein: 128, carbs: 80, fat: 38, fiber: 7, sodium: 570 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "lamb-shoulder-slow-cook-tomato-curry-couscous",
          name: "Lamb Shoulder Slow-Cook with Tomato Curry and Couscous",
          description: "Slow-cooked diced lamb shoulder in rich tomato herb curry sauce with carrots and spinach, served over couscous.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-shoulder", name: "Lamb shoulder, diced", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "carrots", name: "Carrots, chunked", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["slow-cooker", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 690, protein: 54, carbs: 46, fat: 34, fiber: 5, sodium: 350 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Brown lamb shoulder pieces in hot pan 4-5 min",
            "Transfer to slow cooker with carrots and tomato curry sauce",
            "Slow cook 4-6 hrs low (or oven braise at 160C, 2 hrs)",
            "Stir in spinach in last 5 min",
            "Prepare couscous with boiling water, serve lamb over couscous",
          ],
        },
        {
          slug: "chicken-thigh-med-herbs-eggplant-baby-potatoes",
          name: "Chicken Thigh with Mediterranean Herbs, Roasted Eggplant and Baby Potatoes",
          description: "Mediterranean herb chicken thighs on a tray with roasted eggplant, baby potatoes and cherry tomatoes.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "eggplant", name: "Eggplant, cubed", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["oven"],
          cookTime: 30,
          difficulty: "intermediate",
          nutrition: { calories: 648, protein: 58, carbs: 34, fat: 32, fiber: 6, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Preheat oven to 200C",
            "Toss eggplant, baby potatoes and tomatoes with oil on a tray",
            "Coat chicken thighs in Mediterranean herb marinade, place on top",
            "Roast 25-30 min until chicken is golden and vegetables tender",
          ],
        },
      ],
      dailyTotals: { calories: 1338, protein: 112, carbs: 80, fat: 66, fiber: 11, sodium: 660 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "lamb-chops-asparagus-sweet-potato-med",
          name: "Lamb Chops with Asparagus and Sweet Potato",
          description:
            "Three lamb chops, salt and pepper, pan-seared. Grilled asparagus and roasted sweet potato wedges. Simple Mediterranean plate.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 120, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 680, protein: 56, carbs: 26, fat: 42, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato wedges at 200C for 15 min",
            "Heat pan to high with olive oil, season lamb chops",
            "Sear lamb chops 3 min per side",
            "Grill asparagus in same pan 3-4 min",
            "Squeeze lemon over lamb, plate with sweet potato and asparagus",
          ],
        },
        {
          slug: "chicken-breast-coconut-curry-brown-rice-spinach-med",
          name: "Chicken Breast with Coconut Curry, Brown Rice and Spinach",
          description: "Diced chicken breast in coconut curry sauce with baby spinach over brown rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, diced", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 570, protein: 68, carbs: 40, fat: 15, fiber: 5, sodium: 340 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan, cook diced chicken 4-5 min",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over brown rice",
          ],
        },
      ],
      dailyTotals: { calories: 1250, protein: 124, carbs: 66, fat: 57, fiber: 10, sodium: 600 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "lamb-mince-tomato-curry-white-rice",
          name: "Lamb Mince with Tomato Curry and White Rice",
          description: "Lamb mince simmered in tomato herb curry sauce with baby spinach over white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-mince", name: "Lamb mince", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 742, protein: 40, carbs: 52, fat: 44, fiber: 3, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Brown lamb mince in hot pan 5-6 min",
            "Add tomato curry sauce, simmer 8-10 min",
            "Stir in spinach until wilted",
            "Serve over white rice",
          ],
        },
        {
          slug: "chicken-thigh-chimichurri-peppers-pasta-med",
          name: "Chicken Thigh with Chimichurri, Roasted Peppers and Pasta",
          description: "Pan-fried chicken thighs drizzled with chimichurri, with roasted peppers and penne pasta.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 680, protein: 62, carbs: 34, fat: 34, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Pan-fry chicken thighs 5-6 min per side",
            "Roast peppers in same pan 3-4 min",
            "Slice chicken, toss with pasta and peppers",
            "Drizzle chimichurri over the top",
          ],
        },
      ],
      dailyTotals: { calories: 1422, protein: 102, carbs: 86, fat: 78, fiber: 6, sodium: 690 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "lamb-cutlets-shawarma-couscous-roasted-veg",
          name: "Lamb Cutlets with Shawarma Spice, Couscous and Roasted Vegetables",
          description: "Shawarma-spiced lamb cutlets with fluffy couscous and roasted zucchini and cherry tomatoes.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-cutlets", name: "Lamb cutlets (x3)", quantity: 210, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 40, unit: "g", category: "vegetable" },
            { ingredientId: "shawarma", name: "Shawarma spice pouch", quantity: 10, unit: "g", category: "sauce" },
          ],
          sauceCode: "shawarma",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 728, protein: 58, carbs: 36, fat: 42, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub lamb cutlets with shawarma spice and olive oil",
            "Pan-sear 3 min per side",
            "Prepare couscous with boiling water",
            "Roast zucchini and tomatoes 10 min at 200C",
            "Plate couscous with cutlets and roasted vegetables",
          ],
        },
        {
          slug: "lamb-leg-steak-garlic-herb-butter-baby-potatoes-green-beans",
          name: "Lamb Leg Steak with Garlic Herb Butter, Baby Potatoes and Green Beans",
          description: "Pan-seared lamb leg steak topped with garlic herb butter, with baby potatoes and steamed green beans.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 160, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 120, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 628, protein: 60, carbs: 32, fat: 30, fiber: 6, sodium: 350 },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high, season lamb leg steak",
            "Sear 4 min per side, rest 3 min",
            "Top with garlic herb butter",
            "Steam green beans 4 min",
            "Plate potatoes, lamb with melting butter and green beans",
          ],
        },
      ],
      dailyTotals: { calories: 1356, protein: 118, carbs: 68, fat: 72, fiber: 9, sodium: 660 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "lamb-shoulder-med-herbs-roasted-root-veg",
          name: "Lamb Shoulder with Mediterranean Herbs and Roasted Root Vegetables",
          description:
            "Slow-cooked lamb shoulder rubbed in Mediterranean herbs, falling apart tender. Roasted carrots, baby potatoes and zucchini.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-shoulder", name: "Lamb shoulder, diced", quantity: 220, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "carrots", name: "Carrots, chunked", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "zucchini", name: "Zucchini, chunked", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["slow-cooker", "oven"],
          cookTime: 20,
          difficulty: "intermediate",
          nutrition: { calories: 720, protein: 58, carbs: 32, fat: 40, fiber: 6, sodium: 310 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Rub lamb shoulder with Mediterranean herb marinade",
            "Brown in hot pan 4-5 min",
            "Transfer to slow cooker with baby potatoes, carrots and zucchini",
            "Slow cook 4-6 hrs low (or oven braise at 160C, 2 hrs)",
            "Plate lamb with roasted vegetables",
          ],
        },
        {
          slug: "chicken-breast-lemon-herb-salad-sweet-potato-med",
          name: "Chicken Breast with Lemon Herb, Mixed Salad and Sweet Potato",
          description: "Grilled chicken breast with lemon herb dressing over mixed salad with cherry tomatoes, cucumber and sweet potato.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "cucumber", name: "Cucumber, sliced", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "intermediate",
          nutrition: { calories: 498, protein: 65, carbs: 26, fat: 16, fiber: 5, sodium: 340 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 12 min",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Arrange salad, tomatoes and cucumber on plate",
            "Slice chicken over salad, add sweet potato",
            "Drizzle lemon herb dressing",
          ],
        },
      ],
      dailyTotals: { calories: 1218, protein: 123, carbs: 58, fat: 56, fiber: 11, sodium: 650 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1380, protein: 116, carbs: 70, fat: 72, fiber: 9, sodium: 620 } },
      { day: "Tuesday", nutrition: { calories: 1162, protein: 128, carbs: 80, fat: 38, fiber: 7, sodium: 570 } },
      { day: "Wednesday", nutrition: { calories: 1338, protein: 112, carbs: 80, fat: 66, fiber: 11, sodium: 660 } },
      { day: "Thursday", nutrition: { calories: 1250, protein: 124, carbs: 66, fat: 57, fiber: 10, sodium: 600 } },
      { day: "Friday", nutrition: { calories: 1422, protein: 102, carbs: 86, fat: 78, fiber: 6, sodium: 690 } },
      { day: "Saturday", nutrition: { calories: 1356, protein: 118, carbs: 68, fat: 72, fiber: 9, sodium: 660 } },
      { day: "Sunday", nutrition: { calories: 1218, protein: 123, carbs: 58, fat: 56, fiber: 11, sodium: 650 } },
    ],
    average: { calories: 1304, protein: 118, carbs: 73, fat: 63, fiber: 9, sodium: 636 },
  },
};
