import type { Plan } from "@/types";

export const theClassicPlan: Plan = {
  slug: "the-classic",
  name: "The Classic",
  tagline: "Balanced family meals. Honest food done right.",
  goal: "balanced",
  description:
    "The family all-rounder. Mixed proteins, seasonal veg, honest food. Good mix of sauced and simple meals. Includes breakfast — oats, protein pancakes, eggs.",
  difficulty: "beginner",
  targetCalories: 2200,
  macroSplit: { protein: 30, carbs: 45, fat: 25 },
  mealsPerDay: 3,
  includesBreakfast: true,
  durationOptions: [3, 5, 7],
  servingOptions: [1, 2, 4],
  proteinTypes: ["chicken", "beef", "lamb"],
  dietaryOptions: ["gf", "df", "lf"],
  featured: true,
  days: [
    {
      day: 1,
      dayName: "Monday",
      meals: [
        {
          slug: "rolled-oats-banana",
          name: "Rolled Oats with Banana",
          description: "Warm rolled oats topped with sliced banana and a drizzle of raw honey. Simple, filling breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 5,
          difficulty: "beginner",
          nutrition: { calories: 430, protein: 12, carbs: 76, fat: 7, fiber: 9, sodium: 10 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Add oats to a pot with water or milk, cook 3-5 min stirring",
            "Top with sliced banana and drizzle of honey",
          ],
        },
        {
          slug: "classic-chicken-breast-white-rice-steamed-veg",
          name: "Chicken Breast with White Rice and Steamed Vegetables",
          description: "Grilled chicken breast with salt and pepper. White rice, steamed broccoli and carrots. Honest family food.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "carrots", name: "Carrots, sliced", quantity: 60, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 530, protein: 60, carbs: 48, fat: 12, fiber: 5, sodium: 220 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Season chicken breast with salt and pepper, pan-fry 5-6 min per side",
            "Steam broccoli and carrots 4-5 min",
            "Plate rice, chicken and steamed vegetables",
          ],
        },
        {
          slug: "beef-mince-tomato-curry-pasta-spinach",
          name: "Beef Mince with Tomato Curry Sauce, Pasta and Spinach",
          description: "Rich beef mince in tomato herb curry sauce stirred through pasta with baby spinach.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "beef-mince-regular", name: "Beef mince (15%)", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "pasta", name: "Pasta (penne)", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 618, protein: 42, carbs: 52, fat: 28, fiber: 4, sodium: 380 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook pasta per packet instructions",
            "Brown beef mince in a hot pan 5-6 min",
            "Add tomato curry sauce, simmer 8-10 min",
            "Stir in spinach until wilted",
            "Toss through cooked pasta",
          ],
        },
      ],
      dailyTotals: { calories: 1578, protein: 114, carbs: 176, fat: 47, fiber: 18, sodium: 610 },
    },
    {
      day: 2,
      dayName: "Tuesday",
      meals: [
        {
          slug: "protein-pancakes-tuesday",
          name: "Protein Pancakes",
          description: "Fluffy protein pancakes drizzled with raw honey. Quick, high-protein breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 150, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 332, protein: 34, carbs: 30, fat: 7, fiber: 3, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Drizzle with honey",
          ],
        },
        {
          slug: "lamb-leg-steak-baby-potatoes-green-beans",
          name: "Lamb Leg Steak with Baby Potatoes and Green Beans",
          description: "Pan-seared lamb leg steak with salt, pepper and lemon. Baby potatoes and green beans.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-leg-steak", name: "Lamb leg steak", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 452, protein: 49, carbs: 29, fat: 17, fiber: 6, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season lamb with salt and pepper",
            "Sear lamb leg steak 4 min per side",
            "Steam green beans 4 min",
            "Squeeze lemon over lamb, plate with potatoes and beans",
          ],
        },
        {
          slug: "smoky-bbq-chicken-thigh-sweet-potato-corn",
          name: "Smoky BBQ Chicken Thigh with Sweet Potato and Corn",
          description: "BBQ-glazed chicken thighs with roasted sweet potato wedges and charred corn.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, wedges", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "corn", name: "Sweet corn", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "smoky-bbq", name: "Smoky BBQ marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "smoky-bbq",
          cookingMethods: ["air-fryer", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 588, protein: 54, carbs: 50, fat: 22, fiber: 6, sodium: 420 },
          allergens: ["mustard"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Coat chicken thighs in smoky BBQ marinade",
            "Arrange sweet potato wedges on tray",
            "Air fry or oven bake at 200C for 18-20 min",
            "Char corn in a dry pan 3-4 min",
            "Plate chicken, sweet potato and corn",
          ],
        },
      ],
      dailyTotals: { calories: 1372, protein: 137, carbs: 109, fat: 46, fiber: 15, sodium: 880 },
    },
    {
      day: 3,
      dayName: "Wednesday",
      meals: [
        {
          slug: "oats-with-eggs",
          name: "Oats with Eggs",
          description: "Warm rolled oats paired with two scrambled free-range eggs. Protein and carbs to start the day.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x2)", quantity: 120, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 490, protein: 25, carbs: 56, fat: 18, fiber: 8, sodium: 200 },
          allergens: ["gluten", "eggs"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook oats with water or milk 3-5 min",
            "Scramble eggs in a separate pan with butter 2-3 min",
            "Serve oats in bowl with eggs on the side",
          ],
        },
        {
          slug: "beef-rump-chimichurri-salad-sweet-potato",
          name: "Beef Rump Steak with Chimichurri, Mixed Salad and Sweet Potato",
          description: "Pan-seared rump steak drizzled with chimichurri over mixed salad with roasted sweet potato.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump steak", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "chimichurri", name: "Chimichurri pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "chimichurri",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 478, protein: 48, carbs: 24, fat: 22, fiber: 5, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 15 min",
            "Heat pan to high, season rump with salt and pepper",
            "Sear 3-4 min per side for medium",
            "Rest steak 3 min, slice against the grain",
            "Arrange salad, tomatoes, sweet potato, top with steak and chimichurri",
          ],
        },
        {
          slug: "chicken-breast-coconut-curry-brown-rice-classic",
          name: "Chicken Breast Coconut Curry with Brown Rice",
          description: "Diced chicken breast in coconut curry sauce with baby spinach, served over brown rice.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast, diced", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "coconut-curry", name: "Coconut curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "coconut-curry",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 548, protein: 60, carbs: 40, fat: 15, fiber: 4, sodium: 340 },
          allergens: ["tree-nut"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Heat pan, cook diced chicken 4-5 min",
            "Pour in coconut curry sauce, simmer 5 min",
            "Stir in spinach until wilted",
            "Serve over brown rice",
          ],
        },
      ],
      dailyTotals: { calories: 1516, protein: 133, carbs: 120, fat: 55, fiber: 17, sodium: 840 },
    },
    {
      day: 4,
      dayName: "Thursday",
      meals: [
        {
          slug: "protein-pancakes-banana-thursday",
          name: "Protein Pancakes with Banana",
          description: "Fluffy protein pancakes topped with sliced banana. Quick high-protein start.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 150, unit: "g", category: "breakfast" },
            { ingredientId: "banana", name: "Banana, sliced", quantity: 80, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 8,
          difficulty: "beginner",
          nutrition: { calories: 365, protein: 34, carbs: 44, fat: 7, fiber: 4, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Top with sliced banana",
          ],
        },
        {
          slug: "chicken-thigh-peri-peri-white-rice-broccoli",
          name: "Chicken Thigh with Peri-Peri, White Rice and Broccoli",
          description: "Peri-peri marinated chicken thigh with fluffy white rice and steamed broccoli.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "peri-peri", name: "Peri-peri marinade pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "peri-peri",
          cookingMethods: ["air-fryer", "pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 602, protein: 56, carbs: 48, fat: 22, fiber: 4, sodium: 380 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Coat chicken thigh in peri-peri marinade",
            "Air fry at 200C for 15 min or pan-fry 5-6 min per side",
            "Steam broccoli 4 min",
            "Plate rice, chicken and broccoli",
          ],
        },
        {
          slug: "lamb-chops-baby-potatoes-asparagus",
          name: "Lamb Chops with Baby Potatoes and Asparagus",
          description: "Pan-seared lamb chops with baby potatoes and grilled asparagus. Simple and satisfying.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "lamb-chops", name: "Lamb chops (x2)", quantity: 150, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "asparagus", name: "Asparagus spears", quantity: 100, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 480, protein: 40, carbs: 28, fat: 25, fiber: 5, sodium: 260 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Heat pan to high with oil, season lamb chops",
            "Sear lamb chops 3 min per side",
            "Grill asparagus in same pan 3-4 min",
            "Plate potatoes, lamb chops and asparagus",
          ],
        },
      ],
      dailyTotals: { calories: 1447, protein: 130, carbs: 120, fat: 54, fiber: 13, sodium: 840 },
    },
    {
      day: 5,
      dayName: "Friday",
      meals: [
        {
          slug: "rolled-oats-honey-friday",
          name: "Rolled Oats with Honey",
          description: "Simple warm oats drizzled with raw honey. Quick and filling.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 80, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 15, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 3,
          difficulty: "beginner",
          nutrition: { calories: 348, protein: 10, carbs: 64, fat: 5, fiber: 8, sodium: 5 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Add oats to a pot with water, microwave or cook on stovetop 3 min",
            "Drizzle with honey",
          ],
        },
        {
          slug: "beef-sirloin-garlic-herb-butter-mash-green-beans",
          name: "Beef Sirloin with Garlic Herb Butter, Mashed Potato and Green Beans",
          description: "Pan-seared sirloin topped with garlic herb butter, creamy mashed potato and steamed green beans.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-sirloin", name: "Beef sirloin steak", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "white-potato", name: "White potato, for mash", quantity: 180, unit: "g", category: "carb" },
            { ingredientId: "green-beans", name: "Green beans, trimmed", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "garlic-herb-butter", name: "Garlic herb butter pouch", quantity: 30, unit: "g", category: "sauce" },
          ],
          sauceCode: "garlic-herb-butter",
          cookingMethods: ["pan"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 580, protein: 48, carbs: 36, fat: 30, fiber: 5, sodium: 350 },
          allergens: ["dairy"],
          dietary: { gf: "yes", df: "no", lf: "yes" },
          cookingSteps: [
            "Boil potato until soft, mash with salt and pepper",
            "Heat pan to high, season sirloin",
            "Sear 3-4 min per side for medium, rest 3 min",
            "Top steak with garlic herb butter",
            "Steam green beans 4 min",
            "Plate mash, steak with melting butter and green beans",
          ],
        },
        {
          slug: "chicken-breast-med-herbs-couscous-roasted-veg",
          name: "Chicken Breast with Mediterranean Herbs, Couscous and Roasted Vegetables",
          description: "Mediterranean herb-marinated chicken breast with fluffy couscous and roasted zucchini and peppers.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "couscous", name: "Couscous", quantity: 100, unit: "g", category: "carb" },
            { ingredientId: "zucchini", name: "Zucchini, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "sweet-peppers", name: "Sweet peppers, sliced", quantity: 60, unit: "g", category: "vegetable" },
            { ingredientId: "med-herb", name: "Mediterranean herb marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "med-herb",
          cookingMethods: ["pan", "oven"],
          cookTime: 20,
          difficulty: "beginner",
          nutrition: { calories: 520, protein: 62, carbs: 34, fat: 14, fiber: 3, sodium: 310 },
          allergens: ["gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Marinate chicken in Mediterranean herbs",
            "Pan-fry chicken 5-6 min per side",
            "Prepare couscous with boiling water",
            "Roast zucchini and peppers in same pan",
            "Fluff couscous, plate with sliced chicken and roasted vegetables",
          ],
        },
      ],
      dailyTotals: { calories: 1448, protein: 120, carbs: 134, fat: 49, fiber: 16, sodium: 665 },
    },
    {
      day: 6,
      dayName: "Saturday",
      meals: [
        {
          slug: "eggs-with-toast",
          name: "Eggs with Toast",
          description: "Three scrambled free-range eggs with two slices of toasted sourdough. Simple Saturday breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "free-range-eggs", name: "Free-range eggs (x3)", quantity: 180, unit: "g", category: "breakfast" },
            { ingredientId: "sourdough", name: "Sourdough bread (x2 slices)", quantity: 80, unit: "g", category: "carb" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 5,
          difficulty: "beginner",
          nutrition: { calories: 418, protein: 25, carbs: 34, fat: 20, fiber: 2, sodium: 400 },
          allergens: ["eggs", "gluten"],
          dietary: { gf: "no", df: "yes", lf: "yes" },
          cookingSteps: [
            "Toast sourdough slices",
            "Scramble eggs in a pan with butter 2-3 min",
            "Serve eggs on toast",
          ],
        },
        {
          slug: "korean-beef-strips-white-rice-broccoli-classic",
          name: "Korean Beef Strips with White Rice and Broccoli",
          description: "Thin beef strips stir-fried in Korean marinade with broccoli over white rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "beef-rump", name: "Beef rump, thin strips", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "white-rice", name: "White rice", quantity: 130, unit: "g", category: "carb" },
            { ingredientId: "broccoli", name: "Broccoli florets", quantity: 100, unit: "g", category: "vegetable" },
            { ingredientId: "korean", name: "Korean marinade pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "korean",
          cookingMethods: ["pan"],
          cookTime: 15,
          difficulty: "beginner",
          nutrition: { calories: 520, protein: 50, carbs: 46, fat: 17, fiber: 4, sodium: 500 },
          allergens: ["soy", "sesame"],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook white rice per packet instructions",
            "Heat pan to high, stir-fry beef strips 3-4 min",
            "Add Korean marinade and broccoli, toss 2-3 min",
            "Serve over rice",
          ],
        },
        {
          slug: "chicken-thigh-sweet-potato-spinach-classic",
          name: "Chicken Thigh with Sweet Potato and Spinach",
          description: "Pan-fried chicken thighs, salt and pepper only. Roasted sweet potato and wilted spinach. Simple Saturday dinner.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-thigh", name: "Chicken thigh, boneless (x2)", quantity: 200, unit: "g", category: "protein" },
            { ingredientId: "sweet-potato", name: "Sweet potato, cubed", quantity: 150, unit: "g", category: "carb" },
            { ingredientId: "spinach", name: "Baby spinach", quantity: 80, unit: "g", category: "vegetable" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 538, protein: 50, carbs: 32, fat: 24, fiber: 5, sodium: 300 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Roast sweet potato cubes at 200C for 15 min",
            "Season chicken thighs, pan-fry 5-6 min per side",
            "Wilt spinach in pan with residual heat",
            "Plate sweet potato, chicken and spinach",
          ],
        },
      ],
      dailyTotals: { calories: 1476, protein: 125, carbs: 112, fat: 61, fiber: 11, sodium: 1200 },
    },
    {
      day: 7,
      dayName: "Sunday",
      meals: [
        {
          slug: "protein-pancakes-oats-sunday",
          name: "Protein Pancakes with Oats",
          description: "Protein pancakes mixed with oats and drizzled with honey. Hearty Sunday breakfast.",
          slot: "breakfast",
          ingredients: [
            { ingredientId: "protein-pancake-batter", name: "Protein pancake batter", quantity: 150, unit: "g", category: "breakfast" },
            { ingredientId: "rolled-oats", name: "Rolled oats", quantity: 60, unit: "g", category: "breakfast" },
            { ingredientId: "honey", name: "Raw honey sachet", quantity: 10, unit: "g", category: "breakfast" },
          ],
          sauceCode: null,
          cookingMethods: ["pan"],
          cookTime: 10,
          difficulty: "beginner",
          nutrition: { calories: 490, protein: 40, carbs: 64, fat: 10, fiber: 8, sodium: 200 },
          allergens: ["gluten", "eggs", "dairy"],
          dietary: { gf: "no", df: "no", lf: "swap" },
          cookingSteps: [
            "Mix oats into pancake batter",
            "Heat pan to medium with a touch of oil",
            "Pour batter into 3-4 pancakes",
            "Cook 2-3 min per side until golden",
            "Drizzle with honey",
          ],
        },
        {
          slug: "lamb-shoulder-tomato-curry-brown-rice-carrots",
          name: "Lamb Shoulder with Tomato Curry, Brown Rice and Carrots",
          description: "Slow-cooked diced lamb shoulder in tomato herb curry sauce with chunked carrots over brown rice.",
          slot: "lunch",
          ingredients: [
            { ingredientId: "lamb-shoulder", name: "Lamb shoulder, diced", quantity: 160, unit: "g", category: "protein" },
            { ingredientId: "brown-rice", name: "Brown rice", quantity: 120, unit: "g", category: "carb" },
            { ingredientId: "carrots", name: "Carrots, chunked", quantity: 80, unit: "g", category: "vegetable" },
            { ingredientId: "tomato-curry", name: "Tomato herb curry sauce pouch", quantity: 50, unit: "g", category: "sauce" },
          ],
          sauceCode: "tomato-curry",
          cookingMethods: ["pan", "slow-cooker"],
          cookTime: 25,
          difficulty: "beginner",
          nutrition: { calories: 548, protein: 44, carbs: 48, fat: 22, fiber: 5, sodium: 340 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Cook brown rice per packet instructions",
            "Brown lamb shoulder pieces in hot pan 4-5 min",
            "Add carrots and tomato curry sauce, simmer 15-20 min (or slow cook 4 hrs)",
            "Serve over brown rice",
          ],
        },
        {
          slug: "chicken-breast-lemon-herb-baby-potatoes-salad",
          name: "Chicken Breast with Lemon Herb, Baby Potatoes and Mixed Salad",
          description: "Grilled chicken breast with lemon herb dressing, baby potatoes and a fresh mixed salad.",
          slot: "dinner",
          ingredients: [
            { ingredientId: "chicken-breast", name: "Chicken breast", quantity: 180, unit: "g", category: "protein" },
            { ingredientId: "baby-potatoes", name: "Baby potatoes, halved", quantity: 140, unit: "g", category: "carb" },
            { ingredientId: "mixed-salad", name: "Mixed salad leaves", quantity: 50, unit: "g", category: "vegetable" },
            { ingredientId: "cherry-tomatoes", name: "Cherry tomatoes", quantity: 30, unit: "g", category: "vegetable" },
            { ingredientId: "lemon-herb", name: "Lemon herb dressing pouch", quantity: 25, unit: "g", category: "sauce" },
          ],
          sauceCode: "lemon-herb",
          cookingMethods: ["pan"],
          cookTime: 18,
          difficulty: "beginner",
          nutrition: { calories: 490, protein: 61, carbs: 29, fat: 16, fiber: 4, sodium: 340 },
          allergens: [],
          dietary: { gf: "yes", df: "yes", lf: "yes" },
          cookingSteps: [
            "Boil baby potatoes 10 min until tender",
            "Season chicken breast, pan-fry 5-6 min per side",
            "Arrange salad and tomatoes on plate",
            "Slice chicken over salad, add potatoes",
            "Drizzle lemon herb dressing",
          ],
        },
      ],
      dailyTotals: { calories: 1528, protein: 145, carbs: 141, fat: 48, fiber: 17, sodium: 880 },
    },
  ],
  weeklySummary: {
    days: [
      { day: "Monday", nutrition: { calories: 1578, protein: 114, carbs: 176, fat: 47, fiber: 18, sodium: 610 } },
      { day: "Tuesday", nutrition: { calories: 1372, protein: 137, carbs: 109, fat: 46, fiber: 15, sodium: 880 } },
      { day: "Wednesday", nutrition: { calories: 1516, protein: 133, carbs: 120, fat: 55, fiber: 17, sodium: 840 } },
      { day: "Thursday", nutrition: { calories: 1447, protein: 130, carbs: 120, fat: 54, fiber: 13, sodium: 840 } },
      { day: "Friday", nutrition: { calories: 1448, protein: 120, carbs: 134, fat: 49, fiber: 16, sodium: 665 } },
      { day: "Saturday", nutrition: { calories: 1476, protein: 125, carbs: 112, fat: 61, fiber: 11, sodium: 1200 } },
      { day: "Sunday", nutrition: { calories: 1528, protein: 145, carbs: 141, fat: 48, fiber: 17, sodium: 880 } },
    ],
    average: { calories: 1481, protein: 129, carbs: 130, fat: 51, fiber: 15, sodium: 845 },
  },
};
